/* USERS */
export const ADD_USER = "ADD_USER";
export const ADD_VEHICLE = "ADD_VEHICLE";
export const SEND_QUOTE = "SEND_QUOTE";
export const SEND_QUOTE_SUCCESS = "SEND_QUOTE_SUCCESS";
export const SEND_QUOTE_ERROR = "SEND_QUOTE_ERROR";
export const SEND_TRANSMISSION = "SEND_TRANSMISSION";
export const SEND_TRANSMISSION_SUCCESS = "SEND_TRANSMISSION_SUCCESS";
export const SEND_TRANSMISSION_ERROR = "SEND_TRANSMISSION_ERROR";
export const GET_TRANSMISSION_RESPONSE = "GET_TRANSMISSION_RESPONSE";
export const SEND_TRANSMISSION_BEGIN = "SEND_TRANSMISSION_BEGIN";
export const GET_TRANSMISSION_LOADING = "GET_TRANSMISSION_LOADING";
export const REDIRECT_TRANSMISSION_SUCCESS = "REDIRECT_TRANSMISSION_SUCCESS";
export const GET_TRANSMISSION_LOADING_ERROR = "GET_TRANSMISSION_LOADING_ERROR";
export const ADD_LEAD = "ADD_LEAD";
