export const occupations = [
  {
    value: "Não informado",
    label: "Não informado",
  },
  {
    value: "ACOUGUEIRO",
    label: "ACOUGUEIRO",
  },
  {
    value: "ADESTRADOR DE CÃES",
    label: "ADESTRADOR DE CÃES",
  },
  {
    value: "ADM EMPRESA CHEFE ALMOXARIFADO",
    label: "ADM EMPRESA CHEFE ALMOXARIFADO",
  },
  {
    value: "ADM EMPRESAS - COM. EXTERIOR",
    label: "ADM EMPRESAS - COM. EXTERIOR",
  },
  {
    value: "ADM EMPRESAS - MARKETING",
    label: "ADM EMPRESAS - MARKETING",
  },
  {
    value: "ADM EMPRESAS ELETRO ELETRONICO",
    label: "ADM EMPRESAS ELETRO ELETRONICO",
  },
  {
    value: "ADM. DE EMPRESA - IMPORT/EXPO",
    label: "ADM. DE EMPRESA - IMPORT/EXPO",
  },
  {
    value: "ADM. EMPRESA - CARTAO CREDITO",
    label: "ADM. EMPRESA - CARTAO CREDITO",
  },
  {
    value: "ADM. EMPRESA - CONSULTORIA",
    label: "ADM. EMPRESA - CONSULTORIA",
  },
  {
    value: "ADM. EMPRESA - RECURSO HUMANOS",
    label: "ADM. EMPRESA - RECURSO HUMANOS",
  },
  {
    value: "DM. EMPRESAS - AG. DE TURISMO",
    label: "DM. EMPRESAS - AG. DE TURISMO",
  },
  {
    value: "ADM. EMPRESAS - EDITORA",
    label: "ADM. EMPRESAS - EDITORA",
  },
  {
    value: "ADM. EMPRESAS - EMBALAGENS",
    label: "ADM. EMPRESAS - EMBALAGENS",
  },
  {
    value: "ADM. EMPRESAS - LIMPEZA",
    label: "ADM. EMPRESAS - LIMPEZA",
  },
  {
    value: "ADM. EMPRESAS - RAMO ESCOLA",
    label: "ADM. EMPRESAS - RAMO ESCOLA",
  },
  {
    value: "DM. EMPRESAS - RAMO SEGURANÇA",
    label: "DM. EMPRESAS - RAMO SEGURANÇA",
  },
  {
    value: "ADM.DE EMPRESAS-EMP.BORRACHA",
    label: "ADM.DE EMPRESAS-EMP.BORRACHA",
  },
  {
    value: "ADM.EMPR. - INST. ELETRICAS",
    label: "ADM.EMPR. - INST. ELETRICAS",
  },
  {
    value: "ADM.EMPRESA - TELECOMUNICACOES",
    label: "ADM.EMPRESA - TELECOMUNICACOES",
  },
  {
    value: "ADM.EMPRESA-RAMO  ALIMENTÍCIO",
    label: "ADM.EMPRESA-RAMO  ALIMENTÍCIO",
  },
  {
    value: "ADM.EMPRESA-VENDA/LOCAÇÃO VEIC",
    label: "ADM.EMPRESA-VENDA/LOCAÇÃO VEIC",
  },
  {
    value: "ADM.EMPRESAS - RAMO SEGUROS",
    label: "ADM.EMPRESAS - RAMO SEGUROS",
  },
  {
    value: "ADMINISTRADOR - BINGO",
    label: "ADMINISTRADOR - BINGO",
  },
  {
    value: "ADMINISTRADOR - CORREIOS",
    label: "ADMINISTRADOR - CORREIOS",
  },
  {
    value: "ADMINISTRADOR - FAZENDAS",
    label: "ADMINISTRADOR - FAZENDAS",
  },
  {
    value: "ADMINISTRADOR - ORG NÃO GORV",
    label: "ADMINISTRADOR - ORG NÃO GORV",
  },
  {
    value: "ADMINISTRADOR DE CONDOMINIO",
    label: "ADMINISTRADOR DE CONDOMINIO",
  },
  {
    value: "ADMINISTRADOR DE EMPRESAS",
    label: "ADMINISTRADOR DE EMPRESAS",
  },
  {
    value: "ADMINISTRADOR ESTOF E COLCHÕES",
    label: "ADMINISTRADOR ESTOF E COLCHÕES",
  },
  {
    value: "ADMINISTRADOR FINANCEIRO",
    label: "ADMINISTRADOR FINANCEIRO",
  },
  {
    value: "ADMINISTRADOR RAMO INFORMATICA",
    label: "ADMINISTRADOR RAMO INFORMATICA",
  },
  {
    value: "ADMINISTRADOR(A) DE BENS",
    label: "ADMINISTRADOR(A) DE BENS",
  },
  {
    value: "ADMINISTRADOR(A) CONSTRUTORA",
    label: "ADMINISTRADOR(A) CONSTRUTORA",
  },
  {
    value: "DMINISTRADORA DE CONTRATOS",
    label: "DMINISTRADORA DE CONTRATOS",
  },
  {
    value: "ADVOGADO",
    label: "ADVOGADO",
  },
  {
    value: "AERONAUTA",
    label: "AERONAUTA",
  },
  {
    value: "AEROVIARIO",
    label: "AEROVIARIO",
  },
  {
    value: "AGENTE DE SAUDE",
    label: "AGENTE DE SAUDE",
  },
  {
    value: "AGENTE DE SEGUROS",
    label: "AGENTE DE SEGUROS",
  },
  {
    value: "AGENTE DE VIAGEM",
    label: "AGENTE DE VIAGEM",
  },
  {
    value: "AGENTE FISCAL DE RENDA",
    label: "AGENTE FISCAL DE RENDA",
  },
  {
    value: "AGENTE PENITENCIÁRIO",
    label: "AGENTE PENITENCIÁRIO",
  },
  {
    value: "AGENTE TEC. DE ESTATISTICA",
    label: "AGENTE TEC. DE ESTATISTICA",
  },
  {
    value: "AGRICULTOR",
    label: "AGRICULTOR",
  },
  {
    value: "AGRONOMO",
    label: "AGRONOMO",
  },
  {
    value: "AGROPECUARISTA",
    label: "AGROPECUARISTA",
  },
  {
    value: "AJUDANTE DE METALURGICA",
    label: "AJUDANTE DE METALURGICA",
  },
  {
    value: "AJUDANTE DE MOTORISTA",
    label: "AJUDANTE DE MOTORISTA",
  },
  {
    value: "AJUDANTE GERAL",
    label: "AJUDANTE GERAL",
  },
  {
    value: "LFAIATE/COSTUREIRA",
    label: "LFAIATE/COSTUREIRA",
  },
  {
    value: "ALINHADOR AUTOMOTIVO",
    label: "ALINHADOR AUTOMOTIVO",
  },
  {
    value: "ALMOXARIFE",
    label: "ALMOXARIFE",
  },
  {
    value: "ANALISTA DE COMÉRCIO EXTERIOR",
    label: "ANALISTA DE COMÉRCIO EXTERIOR",
  },
  {
    value: "ANALISTA DE DEPTO. PESSOAL",
    label: "ANALISTA DE DEPTO. PESSOAL",
  },
  {
    value: "ANALISTA DE MATERIAIS",
    label: "ANALISTA DE MATERIAIS",
  },
  {
    value: "ANALISTA DE PLANEJAMENTO",
    label: "ANALISTA DE PLANEJAMENTO",
  },
  {
    value: "ANALISTA DE PROGRAMACAO",
    label: "ANALISTA DE PROGRAMACAO",
  },
  {
    value: "ANALISTA DE SEGURANÇA",
    label: "ANALISTA DE SEGURANÇA",
  },
  {
    value: "ANALISTA DE SINISTRO",
    label: "ANALISTA DE SINISTRO",
  },
  {
    value: "ANALISTA DE SISTEMAS",
    label: "ANALISTA DE SISTEMAS",
  },
  {
    value: "ANALISTA DE SUPORTE",
    label: "ANALISTA DE SUPORTE",
  },
  {
    value: "ANALISTA DE TACOGRAFO",
    label: "ANALISTA DE TACOGRAFO",
  },
  {
    value: "ANALISTA CONTABIL",
    label: "ANALISTA CONTABIL",
  },
  {
    value: "ANALISTA FINANCEIRO",
    label: "ANALISTA FINANCEIRO",
  },
  {
    value: "ANESTESISTA",
    label: "ANESTESISTA",
  },
  {
    value: "APOSENTADO - DOENÇA/ACIDENTE",
    label: "APOSENTADO - DOENÇA/ACIDENTE",
  },
  {
    value: "APOSENTADO - TEMPO DE SERVIÇO",
    label: "APOSENTADO - TEMPO DE SERVIÇO",
  },
  {
    value: "APOSENTADO / PENSIONISTA",
    label: "APOSENTADO / PENSIONISTA",
  },
  {
    value: "ARMADOR DE FERRAGEM CONST CIV",
    label: "ARMADOR DE FERRAGEM CONST CIV",
  },
  {
    value: "ARQUEÓLOGO",
    label: "ARQUEÓLOGO",
  },
  {
    value: "ARQUITETO",
    label: "ARQUITETO",
  },
  {
    value: "ARRUMADEIRA /CAMAREIRA",
    label: "ARRUMADEIRA /CAMAREIRA",
  },
  {
    value: "ARTESA - CONFECCAO EM LA'",
    label: "ARTESA - CONFECCAO EM LA'",
  },
  {
    value: "ARTESAO",
    label: "ARTESAO",
  },
  {
    value: "ARTISTA PLASTICO",
    label: "ARTISTA PLASTICO",
  },
  {
    value: "ASSESSOR(A)  FINANCEIRO(A)",
    label: "ASSESSOR(A)  FINANCEIRO(A)",
  },
  {
    value: "ASSESSOR(A) DE MARKETING",
    label: "ASSESSOR(A) DE MARKETING",
  },
  {
    value: "ASSESSOR(A) JURÍDICO",
    label: "ASSESSOR(A) JURÍDICO",
  },
  {
    value: "ASSESSOR(A) PARLAMENTAR",
    label: "ASSESSOR(A) PARLAMENTAR",
  },
  {
    value: "ASSESSOR(A) SINDICAL",
    label: "ASSESSOR(A) SINDICAL",
  },
  {
    value: "ASSESSORA DE SEGUROS",
    label: "ASSESSORA DE SEGUROS",
  },
  {
    value: "ASSESSORIA DE MIGRACAO",
    label: "ASSESSORIA DE MIGRACAO",
  },
  {
    value: "ASSISTENTE DE CAMERA",
    label: "ASSISTENTE DE CAMERA",
  },
  {
    value: "ASSISTENTE DE DIRETORIA",
    label: "ASSISTENTE DE DIRETORIA",
  },
  {
    value: "ASSISTENTE DE INVESTIMENTOS",
    label: "ASSISTENTE DE INVESTIMENTOS",
  },
  {
    value: "ASSISTENTE DE PRODUCAO",
    label: "ASSISTENTE DE PRODUCAO",
  },
  {
    value: "ASSISTENTE DE PROGRAMACAO",
    label: "ASSISTENTE DE PROGRAMACAO",
  },
  {
    value: "ASSISTENTE DE TESOURARIA",
    label: "ASSISTENTE DE TESOURARIA",
  },
  {
    value: "ASSISTENTE DE VENDAS",
    label: "ASSISTENTE DE VENDAS",
  },
  {
    value: "ASSISTENTE ADMINISTRATIVO",
    label: "ASSISTENTE ADMINISTRATIVO",
  },
  {
    value: "ASSISTENTE COMERCIAL",
    label: "ASSISTENTE COMERCIAL",
  },
  {
    value: "ASSISTENTE COMERCIO EXTERIOR",
    label: "ASSISTENTE COMERCIO EXTERIOR",
  },
  {
    value: "ASSISTENTE CONTABIL",
    label: "ASSISTENTE CONTABIL",
  },
  {
    value: "ASSISTENTE DEPTO. PESSOAL",
    label: "ASSISTENTE DEPTO. PESSOAL",
  },
  {
    value: "ASSISTENTE EXECUTIVO",
    label: "ASSISTENTE EXECUTIVO",
  },
  {
    value: "ASSISTENTE OPERACIONAL",
    label: "ASSISTENTE OPERACIONAL",
  },
  {
    value: "DASSISTENTE SOCIAL",
    label: "DASSISTENTE SOCIAL",
  },
  {
    value: "ASSISTENTE TECNICO",
    label: "ASSISTENTE TECNICO",
  },
  {
    value: "STRÔNOMO",
    label: "STRÔNOMO",
  },
  {
    value: "ATENDENTE COMERCIAL",
    label: "ATENDENTE COMERCIAL",
  },
  {
    value: "ATENDENTE ENFERMAGEM",
    label: "ATENDENTE ENFERMAGEM",
  },
  {
    value: "ATLETA AMADOR",
    label: "ATLETA AMADOR",
  },
  {
    value: "ATOR /ATRIZ",
    label: "ATOR /ATRIZ",
  },
  {
    value: "ATUÁRIO",
    label: "ATUÁRIO",
  },
  {
    value: "AUDITOR",
    label: "AUDITOR",
  },
  {
    value: "AUTONOMO",
    label: "AUTONOMO",
  },
  {
    value: "AUTONOMO - CARREGADOR",
    label: "AUTONOMO - CARREGADOR",
  },
  {
    value: "AUTONOMO - COBRANCA DE TITULOS",
    label: "AUTONOMO - COBRANCA DE TITULOS",
  },
  {
    value: "AUTONOMO - CRIADOR DE ANIMAIS",
    label: "AUTONOMO - CRIADOR DE ANIMAIS",
  },
  {
    value: "AUTONOMO - MAQUINAS GRAFICAS",
    label: "AUTONOMO - MAQUINAS GRAFICAS",
  },
  {
    value: "AUTONOMO - RAMO MARCENARIA",
    label: "AUTONOMO - RAMO MARCENARIA",
  },
  {
    value: "AUTONOMO - VENDEDOR DE BRINDES",
    label: "AUTONOMO - VENDEDOR DE BRINDES",
  },
  {
    value: "AUTONOMO - VENDEDOR CRISTAIS",
    label: "AUTONOMO - VENDEDOR CRISTAIS",
  },
  {
    value: "AUTONOMO CONSULTOR INFORMATICA",
    label: "AUTONOMO CONSULTOR INFORMATICA",
  },
  {
    value: "AUTONOMO RAMO INVESTIMENTO",
    label: "AUTONOMO RAMO INVESTIMENTO",
  },
  {
    value: "AUTONOMO(A) PROMOTOR(A) EVENTO",
    label: "AUTONOMO(A) PROMOTOR(A) EVENTO",
  },
  {
    value: "AUTONOMO-MANUTENÇÃO HIDRÁULICA",
    label: "AUTONOMO-MANUTENÇÃO HIDRÁULICA",
  },
  {
    value: "AUTOR (A)",
    label: "AUTOR (A)",
  },
  {
    value: "AUTÔNOMO - CULINÁRIA",
    label: "AUTÔNOMO - CULINÁRIA",
  },
  {
    value: "AUTÔNOMO - VENDEDOR DECORAÇÃO",
    label: "AUTÔNOMO - VENDEDOR DECORAÇÃO",
  },
  {
    value: "AUX LARVICULTURA",
    label: "AUX LARVICULTURA",
  },
  {
    value: "AUX. TECNICO DE REFRIGERACAO",
    label: "AUX. TECNICO DE REFRIGERACAO",
  },
  {
    value: "AUXILIAR",
    label: "AUXILIAR",
  },
  {
    value: "AUXILIAR  ESTATIS. TRANSPORTE",
    label: "AUXILIAR  ESTATIS. TRANSPORTE",
  },
  {
    value: "AUXILIAR DE BIBLIOTECA",
    label: "AUXILIAR DE BIBLIOTECA",
  },
  {
    value: "AUXILIAR DE COBRANCA",
    label: "AUXILIAR DE COBRANCA",
  },
  {
    value: "AUXILIAR DE COZINHEIRO ( A )",
    label: "AUXILIAR DE COZINHEIRO ( A )",
  },
  {
    value: "AUXILIAR DE DESELVOLVIMENTO",
    label: "AUXILIAR DE DESELVOLVIMENTO",
  },
  {
    value: "AUXILIAR DE ELETRONICA",
    label: "AUXILIAR DE ELETRONICA",
  },
  {
    value: "AUXILIAR DE ENFERMAGEM",
    label: "AUXILIAR DE ENFERMAGEM",
  },
  {
    value: "AUXILIAR DE ESCRITORIO",
    label: "AUXILIAR DE ESCRITORIO",
  },
  {
    value: "AUXILIAR DE LABORATORIO",
    label: "AUXILIAR DE LABORATORIO",
  },
  {
    value: "AUXILIAR DE MANUTENCAO",
    label: "AUXILIAR DE MANUTENCAO",
  },
  {
    value: "AUXILIAR DE PRODUCAO",
    label: "AUXILIAR DE PRODUCAO",
  },
  {
    value: "AUXILIAR DE PROTETICO",
    label: "AUXILIAR DE PROTETICO",
  },
  {
    value: "AUXILIAR DE SERVIÇOS - LIMPEZA",
    label: "AUXILIAR DE SERVIÇOS - LIMPEZA",
  },
  {
    value: "AUXILIAR DE SERVIÇOS GERAIS",
    label: "AUXILIAR DE SERVIÇOS GERAIS",
  },
  {
    value: "AUXILIAR DE TESOURARIA",
    label: "AUXILIAR DE TESOURARIA",
  },
  {
    value: "AUXILIAR DE TOPOGRAFIA",
    label: "AUXILIAR DE TOPOGRAFIA",
  },
  {
    value: "AUXILIAR ADMINISTRATIVO",
    label: "AUXILIAR ADMINISTRATIVO",
  },
  {
    value: "AUXILIAR COMERCIAL",
    label: "AUXILIAR COMERCIAL",
  },
  {
    value: "AUXILIAR CONTÁBIL",
    label: "AUXILIAR CONTÁBIL",
  },
  {
    value: "AUXILIAR DEPOSITO AUTO-PECAS",
    label: "AUXILIAR DEPOSITO AUTO-PECAS",
  },
  {
    value: "JAUXILIAR DEPOSITO MT. ELETRICO'",
    label: "JAUXILIAR DEPOSITO MT. ELETRICO'",
  },
  {
    value: "UXILIAR DEPTO.  PESSOAL",
    label: "UXILIAR DEPTO.  PESSOAL",
  },
  {
    value: "AUXILIAR DESPACHANTE",
    label: "AUXILIAR DESPACHANTE",
  },
  {
    value: "AUXILIAR FINANCEIRO",
    label: "AUXILIAR FINANCEIRO",
  },
  {
    value: "AUXILIAR JUDICIÁRIO",
    label: "AUXILIAR JUDICIÁRIO",
  },
  {
    value: "AUXILIAR MONTADOR METALURGICA",
    label: "AUXILIAR MONTADOR METALURGICA",
  },
  {
    value: "AUXILIAR NA REDE TELEFONICA",
    label: "AUXILIAR NA REDE TELEFONICA",
  },
  {
    value: "AUXILIAR PRODUCAO - ESTOFADOS",
    label: "AUXILIAR PRODUCAO - ESTOFADOS",
  },
  {
    value: "AUXILIAR TECN. TELECOMUNICACAO",
    label: "AUXILIAR TECN. TELECOMUNICACAO",
  },
  {
    value: "AUXILIAR TECNICO",
    label: "AUXILIAR TECNICO",
  },
  {
    value: "AUXILIAR TRIBUTARIO",
    label: "AUXILIAR TRIBUTARIO",
  },
  {
    value: "AVICULTOR",
    label: "AVICULTOR",
  },
  {
    value: "BABA",
    label: "BABA",
  },
  {
    value: "BAILARINO",
    label: "BAILARINO",
  },
  {
    value: "BALCONISTA",
    label: "BALCONISTA",
  },
  {
    value: "BANCARIO",
    label: "BANCARIO",
  },
  {
    value: "BANQUEIRO",
    label: "BANQUEIRO",
  },
  {
    value: "BARBEIRO",
    label: "BARBEIRO",
  },
  {
    value: "BARMAN",
    label: "BARMAN",
  },
  {
    value: "BIBLIOTECARIO",
    label: "BIBLIOTECARIO",
  },
  {
    value: "BIOLOGO",
    label: "BIOLOGO",
  },
  {
    value: "BIOMEDICA",
    label: "BIOMEDICA",
  },
  {
    value: "BIOQUIMICO (A)",
    label: "BIOQUIMICO (A)",
  },
  {
    value: "BOMBEIRO",
    label: "BOMBEIRO",
  },
  {
    value: "BOMBEIRO HIDRAULICO/ENCANADOR",
    label: "BOMBEIRO HIDRAULICO/ENCANADOR",
  },
  {
    value: "BORRACHEIRO",
    label: "BORRACHEIRO",
  },
  {
    value: "CABELEREIRO(A)",
    label: "CABELEREIRO(A)",
  },
  {
    value: "CADASTRADOR",
    label: "CADASTRADOR",
  },
  {
    value: "CAIXA",
    label: "CAIXA",
  },
  {
    value: "CALHEIRO",
    label: "CALHEIRO",
  },
  {
    value: "CAMAREIRA",
    label: "CAMAREIRA",
  },
  {
    value: "CAMINHONEIRO",
    label: "CAMINHONEIRO",
  },
  {
    value: "CANTINEIRA ESCOLAR",
    label: "CANTINEIRA ESCOLAR",
  },
  {
    value: "CANTOR",
    label: "CANTOR",
  },
  {
    value: "CANTORA",
    label: "CANTORA",
  },
  {
    value: "CARDIOLOGISTA",
    label: "CARDIOLOGISTA",
  },
  {
    value: "CARPINTEIRO",
    label: "CARPINTEIRO",
  },
  {
    value: "CARTEIRO",
    label: "CARTEIRO",
  },
  {
    value: "CARTORARIO",
    label: "CARTORARIO",
  },
  {
    value: "CASEIRO",
    label: "CASEIRO",
  },
  {
    value: "CAVALEIRO",
    label: "CAVALEIRO",
  },
  {
    value: "CENOTECNICO",
    label: "CENOTECNICO",
  },
  {
    value: "CHAVEIRO",
    label: "CHAVEIRO",
  },
  {
    value: "CIENTISTA",
    label: "CIENTISTA",
  },
  {
    value: "CIENTISTA POLITICO",
    label: "CIENTISTA POLITICO",
  },
  {
    value: "CINEASTA",
    label: "CINEASTA",
  },
  {
    value: "CIRURGIAO DENTISTA",
    label: "CIRURGIAO DENTISTA",
  },
  {
    value: "CITRICULTOR",
    label: "CITRICULTOR",
  },
  {
    value: "CLASSIFICADOR DE COURO",
    label: "CLASSIFICADOR DE COURO",
  },
  {
    value: "COBRADOR DE ONIBUS",
    label: "COBRADOR DE ONIBUS",
  },
  {
    value: "COMENTARISTA",
    label: "COMENTARISTA",
  },
  {
    value: "COMERCIÁRIO RAMO TRANSPORTES",
    label: "COMERCIÁRIO RAMO TRANSPORTES",
  },
  {
    value: "COMERCIANTE",
    label: "COMERCIANTE",
  },
  {
    value: "COMERCIANTE  - CONFECCAO",
    label: "COMERCIANTE  - CONFECCAO",
  },
  {
    value: "COMERCIANTE  - RAMO AGRICOLA",
    label: "COMERCIANTE  - RAMO AGRICOLA",
  },
  {
    value: "COMERCIANTE  MATERIAL ELETRICO",
    label: "COMERCIANTE  MATERIAL ELETRICO",
  },
  {
    value: "COMERCIANTE - AGROPECUARIA",
    label: "COMERCIANTE - AGROPECUARIA",
  },
  {
    value: "COMERCIANTE - ARTESANATO",
    label: "COMERCIANTE - ARTESANATO",
  },
  {
    value: "COMERCIANTE - ATACADISTA",
    label: "COMERCIANTE - ATACADISTA",
  },
  {
    value: "COMERCIANTE - AUTO ELETRICO",
    label: "COMERCIANTE - AUTO ELETRICO",
  },
  {
    value: "COMERCIANTE - BALAS E DOCES",
    label: "COMERCIANTE - BALAS E DOCES",
  },
  {
    value: "COMERCIANTE - BANCA DE REVISTA",
    label: "COMERCIANTE - BANCA DE REVISTA",
  },
  {
    value: "COMERCIANTE - BOMBONAS",
    label: "COMERCIANTE - BOMBONAS",
  },
  {
    value: "COMERCIANTE - CAFE",
    label: "COMERCIANTE - CAFE",
  },
  {
    value: "COMERCIANTE - CASA DE RAÇÕES",
    label: "COMERCIANTE - CASA DE RAÇÕES",
  },
  {
    value: "COMERCIANTE - CONSTRUCAO CIVIL",
    label: "COMERCIANTE - CONSTRUCAO CIVIL",
  },
  {
    value: "COMERCIANTE - COUROS",
    label: "COMERCIANTE - COUROS",
  },
  {
    value: "COMERCIANTE - ELETRODOMESTICO",
    label: "COMERCIANTE - ELETRODOMESTICO",
  },
  {
    value: "COMERCIANTE - FARMACIA",
    label: "COMERCIANTE - FARMACIA",
  },
  {
    value: "COMERCIANTE - LJ. DE VEICULOS",
    label: "COMERCIANTE - LJ. DE VEICULOS",
  },
  {
    value: "COMERCIANTE - LJ. ARMARINHOS",
    label: "COMERCIANTE - LJ. ARMARINHOS",
  },
  {
    value: "COMERCIANTE - LJ. CONVENIENCIA",
    label: "COMERCIANTE - LJ. CONVENIENCIA",
  },
  {
    value: "COMERCIANTE - LOJA DE PLANTAS",
    label: "COMERCIANTE - LOJA DE PLANTAS",
  },
  {
    value: "COMERCIANTE - LOJA DE TINTAS",
    label: "COMERCIANTE - LOJA DE TINTAS",
  },
  {
    value: "COMERCIANTE - LOJA PET SHOP",
    label: "COMERCIANTE - LOJA PET SHOP",
  },
  {
    value: "COMERCIANTE - PECAS PARA MOTOS",
    label: "COMERCIANTE - PECAS PARA MOTOS",
  },
  {
    value: "COMERCIANTE - PEDREIRA",
    label: "COMERCIANTE - PEDREIRA",
  },
  {
    value: "COMERCIANTE - PEIXARIA",
    label: "COMERCIANTE - PEIXARIA",
  },
  {
    value: "COMERCIANTE - PLÁSTICOS",
    label: "COMERCIANTE - PLÁSTICOS",
  },
  {
    value: "COMERCIANTE - PROD. ODONTOLOG.",
    label: "COMERCIANTE - PROD. ODONTOLOG.",
  },
  {
    value: "COMERCIANTE - PRODUTOS LIMPEZA",
    label: "COMERCIANTE - PRODUTOS LIMPEZA",
  },
  {
    value: "COMERCIANTE - RAMO DE PADARIAS",
    label: "COMERCIANTE - RAMO DE PADARIAS",
  },
  {
    value: "COMERCIANTE - RAMO ACRÍLICO",
    label: "COMERCIANTE - RAMO ACRÍLICO",
  },
  {
    value: "COMERCIANTE - RAMO BUFFET",
    label: "COMERCIANTE - RAMO BUFFET",
  },
  {
    value: "COMERCIANTE - RAMO CONSTRUCAO",
    label: "COMERCIANTE - RAMO CONSTRUCAO",
  },
  {
    value: "COMERCIANTE - RAMO ELETRÔNICOS",
    label: "COMERCIANTE - RAMO ELETRÔNICOS",
  },
  {
    value: "COMERCIANTE - RAMO IMOBILIARIA",
    label: "COMERCIANTE - RAMO IMOBILIARIA",
  },
  {
    value: "COMERCIANTE - RAMO INFORMATICA",
    label: "COMERCIANTE - RAMO INFORMATICA",
  },
  {
    value: "COMERCIANTE - RAMO JOIAS",
    label: "COMERCIANTE - RAMO JOIAS",
  },
  {
    value: "COMERCIANTE - RECICLAGEM",
    label: "COMERCIANTE - RECICLAGEM",
  },
  {
    value: "COMERCIANTE - SUPERMERCADO",
    label: "COMERCIANTE - SUPERMERCADO",
  },
  {
    value: "COMERCIANTE - TURISMO",
    label: "COMERCIANTE - TURISMO",
  },
  {
    value: "COMERCIANTE - VAREJÃO",
    label: "COMERCIANTE - VAREJÃO",
  },
  {
    value: "COMERCIANTE DE CALCADOS",
    label: "COMERCIANTE DE CALCADOS",
  },
  {
    value: "COMERCIANTE DE CELULARES",
    label: "COMERCIANTE DE CELULARES",
  },
  {
    value: "COMERCIANTE DE JOIAS",
    label: "COMERCIANTE DE JOIAS",
  },
  {
    value: "COMERCIANTE DE LUBRIFICANTES",
    label: "COMERCIANTE DE LUBRIFICANTES",
  },
  {
    value: "COMERCIANTE DE PNEUS",
    label: "COMERCIANTE DE PNEUS",
  },
  {
    value: "COMERCIANTE ABATEDOURO AVES",
    label: "COMERCIANTE ABATEDOURO AVES",
  },
  {
    value: "COMERCIANTE ACESSORIOS P/ AUTO",
    label: "COMERCIANTE ACESSORIOS P/ AUTO",
  },
  {
    value: "COMERCIANTE BAR E RESTAURANTE",
    label: "COMERCIANTE BAR E RESTAURANTE",
  },
  {
    value: "COMERCIANTE CORTINAS/PERSIANAS",
    label: "COMERCIANTE CORTINAS/PERSIANAS",
  },
  {
    value: "COMERCIANTE DEPOSITO DE PAPEL",
    label: "COMERCIANTE DEPOSITO DE PAPEL",
  },
  {
    value: "COMERCIANTE IMPLEM. AGRICOLAS",
    label: "COMERCIANTE IMPLEM. AGRICOLAS",
  },
  {
    value: "COMERCIANTE LJ INSTR. MUSICAIS",
    label: "COMERCIANTE LJ INSTR. MUSICAIS",
  },
  {
    value: "COMERCIANTE LOJA DE REFORMAS",
    label: "COMERCIANTE LOJA DE REFORMAS",
  },
  {
    value: "COMERCIANTE LOUCAS CERAMICAS",
    label: "COMERCIANTE LOUCAS CERAMICAS",
  },
  {
    value: "COMERCIANTE MATERIAL SEGURANCA",
    label: "COMERCIANTE MATERIAL SEGURANCA",
  },
  {
    value: "COMERCIANTE MOVEIS ESCRITORIO",
    label: "COMERCIANTE MOVEIS ESCRITORIO",
  },
  {
    value: "COMERCIANTE PAPELARIA / XEROX",
    label: "COMERCIANTE PAPELARIA / XEROX",
  },
  {
    value: "COMERCIANTE POSTO DE GASOLINA",
    label: "COMERCIANTE POSTO DE GASOLINA",
  },
  {
    value: "TMERCIANTE PRESENTES EM GERAL",
    label: "TMERCIANTE PRESENTES EM GERAL",
  },
  {
    value: "COMERCIANTE RAMO DE ALIMENTOS",
    label: "COMERCIANTE RAMO DE ALIMENTOS",
  },
  {
    value: "COMERCIANTE RAMO EMBALAGENS",
    label: "COMERCIANTE RAMO EMBALAGENS",
  },
  {
    value: "COMERCIANTE RAMO FERRAGENS",
    label: "COMERCIANTE RAMO FERRAGENS",
  },
  {
    value: "COMERCIANTE RAMO MADEIRA",
    label: "COMERCIANTE RAMO MADEIRA",
  },
  {
    value: "COMERCIANTE RAMO RELOJOARIA",
    label: "COMERCIANTE RAMO RELOJOARIA",
  },
  {
    value: "COMERCIANTE SECOS E MOLHADOS",
    label: "COMERCIANTE SECOS E MOLHADOS",
  },
  {
    value: "COMERCIANTE SUCATAS",
    label: "COMERCIANTE SUCATAS",
  },
  {
    value: "COMERCIANTE- FITAS  VIDEO GAME",
    label: "COMERCIANTE- FITAS  VIDEO GAME",
  },
  {
    value: "COMERCIANTE-APARELHOS AUDITIVO",
    label: "COMERCIANTE-APARELHOS AUDITIVO",
  },
  {
    value: "COMERCIANTE-RAMO DE PARAFUSOS",
    label: "COMERCIANTE-RAMO DE PARAFUSOS",
  },
  {
    value: "COMERCIANTE-RAMO DEDETIZAÇÃO",
    label: "COMERCIANTE-RAMO DEDETIZAÇÃO",
  },
  {
    value: "COMERCIANTE-TAPECEIRO DE AUTO",
    label: "COMERCIANTE-TAPECEIRO DE AUTO",
  },
  {
    value: "COMERCIARIO",
    label: "COMERCIARIO",
  },
  {
    value: "COMERCIARIO FUNCIONARIO VAREJO",
    label: "COMERCIARIO FUNCIONARIO VAREJO",
  },
  {
    value: "COMISSARIO(A) DE BORDO",
    label: "COMISSARIO(A) DE BORDO",
  },
  {
    value: "COMPOSITOR",
    label: "COMPOSITOR",
  },
  {
    value: "COMPRADOR",
    label: "COMPRADOR",
  },
  {
    value: "COMUNICOLOGA",
    label: "COMUNICOLOGA",
  },
  {
    value: "CONFEITEIRA",
    label: "CONFEITEIRA",
  },
  {
    value: "CONFERENTE",
    label: "CONFERENTE",
  },
  {
    value: "CONFERENTE PORTUARIO",
    label: "CONFERENTE PORTUARIO",
  },
  {
    value: "CONSELHEIRO TUTELAR",
    label: "CONSELHEIRO TUTELAR",
  },
  {
    value: "CONSTRUTOR CIVIL",
    label: "CONSTRUTOR CIVIL",
  },
  {
    value: "CONSULTOR",
    label: "CONSULTOR",
  },
  {
    value: "CONSULTOR (A) MARKETING",
    label: "CONSULTOR (A) MARKETING",
  },
  { value: "CONSULTOR - TRANSPORTE" ,
    label: "CONSULTOR - TRANSPORTE" },
  { value: "CONSULTOR DE MODA" ,
    label: "CONSULTOR DE MODA" },
  { value: "CONSULTOR DE RECURSOS HUMANOS" ,
    label: "CONSULTOR DE RECURSOS HUMANOS" },
  { value: "CONSULTOR DE VENDAS" ,
    label: "CONSULTOR DE VENDAS" },
  { value: "CONSULTOR EM INFORMATICA" ,
    label: "CONSULTOR EM INFORMATICA" },
  { value: "CONSULTOR EM PLANOS PRODUCAO" ,
    label: "CONSULTOR EM PLANOS PRODUCAO" },
  { value: "CONSULTOR ADMINISTRATIVO" ,
    label: "CONSULTOR ADMINISTRATIVO" },
  { value: "CONSULTOR EMPRESARIAL" ,
    label: "CONSULTOR EMPRESARIAL" },
  { value: "CONSULTOR FINANCEIRO" ,
    label: "CONSULTOR FINANCEIRO" },
  { value: "CONSULTOR IMOBILIARIO" ,
    label: "CONSULTOR IMOBILIARIO" },
  { value: "CONSULTOR INDUSTRIAL" ,
    label: "CONSULTOR INDUSTRIAL" },
  { value: "CONSULTOR JURIDICO" ,
    label: "CONSULTOR JURIDICO" },
  { value: "CONSULTOR TECNICO" ,
    label: "CONSULTOR TECNICO" },
  { value: "CONTABILISTA" ,
    label: "CONTABILISTA" },
  { value: "CONTADOR" ,
    label: "CONTADOR" },
  { value: "CONTINUISTA" ,
    label: "CONTINUISTA" },
  { value: "CONTINUO" ,
    label: "CONTINUO" },
  { value: "CONTROLER" ,
    label: "CONTROLER" },
  { value: "COORDENADOR" ,
    label: "COORDENADOR" },
  { value: "COORDENADOR  DE QUALIDADE" ,
    label: "COORDENADOR  DE QUALIDADE" },
  { value: "COORDENADOR DE ESPORTES" ,
    label: "COORDENADOR DE ESPORTES" },
  { value: "COORDENADOR DE OBRAS" ,
    label: "COORDENADOR DE OBRAS" },
  { value: "COORDENADOR COMERCIAL" ,
    label: "COORDENADOR COMERCIAL" },
  { value: "COORDENADOR ESCOLAR" ,
    label: "COORDENADOR ESCOLAR" },
  { value: "COORDENADOR PROJETOS ESPECIAIS" ,
    label: "COORDENADOR PROJETOS ESPECIAIS" },
  { value: "COPEIRO" ,
    label: "COPEIRO" },
  { value: "COREOGRAFO" ,
    label: "COREOGRAFO" },
  { value: "CORRETOR DE CAFE" ,
    label: "CORRETOR DE CAFE" },
  { value: "CORRETOR DE IMOVEIS" ,
    label: "CORRETOR DE IMOVEIS" },
  { value: "CORRETOR DE SEGUROS" ,
    label: "CORRETOR DE SEGUROS" },
  { value: "CORRETOR DE VALORES" ,
    label: "CORRETOR DE VALORES" },
  { value: "COSTUREIRA (A)" ,
    label: "COSTUREIRA (A)" },
  { value: "COZINHEIRO" ,
    label: "COZINHEIRO" },
  { value: "CUMIN" ,
    label: "CUMIN" },
  { value: "DECORADOR" ,
    label: "DECORADOR" },
  { value: "DELEGADO DE POLICIA" ,
    label: "DELEGADO DE POLICIA" },
  { value: "DEMONSTRADORA-EXPOSIÇÃO  AUTOS" ,
    label: "DEMONSTRADORA-EXPOSIÇÃO  AUTOS" },
  { value: "DENTISTA" ,
    label: "DENTISTA" },
  { value: "DEPILADORA" ,
    label: "DEPILADORA" },
  { value: "DEPUTADO ESTADUAL" ,
    label: "DEPUTADO ESTADUAL" },
  { value: "DEPUTADO FEDERAL" ,
    label: "DEPUTADO FEDERAL" },
  { value: "DESEMBARGADOR" ,
    label: "DESEMBARGADOR" },
  { value: "DESEMPREGADO" ,
    label: "DESEMPREGADO" },
  { value: "DESENHISTA" ,
    label: "DESENHISTA" },
  { value: "DESIGNER" ,
    label: "DESIGNER" },
  { value: "DESPACHANTE" ,
    label: "DESPACHANTE" },
  { value: "DIARISTA" ,
    label: "DIARISTA" },
  { value: "DIGITADORA" ,
    label: "DIGITADORA" },
  { value: "DIPLOMATA" ,
    label: "DIPLOMATA" },
  { value: "DIRETOR DE COMPRAS" ,
    label: "DIRETOR DE COMPRAS" },
  { value: "DIRETOR DE EMPRESA" ,
    label: "DIRETOR DE EMPRESA" },
  { value: "DIRETOR DE ESCOLA" ,
    label: "DIRETOR DE ESCOLA" },
  { value: "DIRETOR DE TV" ,
    label: "DIRETOR DE TV" },
  { value: "DIRETOR DE VENDAS" ,
    label: "DIRETOR DE VENDAS" },
  { value: "DIRETOR ADJUNTO" ,
    label: "DIRETOR ADJUNTO" },
  { value: "DIRETOR AUTO-ESCOLA" ,
    label: "DIRETOR AUTO-ESCOLA" },
  { value: "DIRETOR COMERCIAL" ,
    label: "DIRETOR COMERCIAL" },
  { value: "DIRETOR FINANCEIRO" ,
    label: "DIRETOR FINANCEIRO" },
  { value: "DIRETOR GERAL" ,
    label: "DIRETOR GERAL" },
  { value: "DIRETOR INDUSTRIAL" ,
    label: "DIRETOR INDUSTRIAL" },
  { value: "DIRETOR LEGISLATIVO" ,
    label: "DIRETOR LEGISLATIVO" },
  { value: "DIRETOR RH" ,
    label: "DIRETOR RH" },
  { value: "DIRETOR SECRETARIO" ,
    label: "DIRETOR SECRETARIO" },
  { value: "DIRETOR SUPERINTENDENTE" ,
    label: "DIRETOR SUPERINTENDENTE" },
  { value: "DIRETOR TECNICO" ,
    label: "DIRETOR TECNICO" },
  { value: "DIRETORA - CASA DE CULTURA" ,
    label: "DIRETORA - CASA DE CULTURA" },
  { value: "DIRETORA PRESIDENTE" ,
    label: "DIRETORA PRESIDENTE" },
  { value: "DIRETORA SINDICAL" ,
    label: "DIRETORA SINDICAL" },
  { value: "DIVULGADORA DE PROD HIGIENICOS" ,
    label: "DIVULGADORA DE PROD HIGIENICOS" },
  { value: "DO LAR" ,
    label: "DO LAR" },
  { value: "ECOLOGISTA" ,
    label: "ECOLOGISTA" },
  { value: "ECONOMISTA" ,
    label: "ECONOMISTA" },
  { value: "EDITOR" ,
    label: "EDITOR" },
  { value: "EDITORA DE VIDEO" ,
    label: "EDITORA DE VIDEO" },
  { value: "ELETRICISTA" ,
    label: "ELETRICISTA" },
  { value: "ELETRICITARIO" ,
    label: "ELETRICITARIO" },
  { value: "ELETROTECNICO" ,
    label: "ELETROTECNICO" },
  { value: "EMBALADOR DE PECAS DE AUTO" ,
    label: "EMBALADOR DE PECAS DE AUTO" },
  { value: "EMPREENDEDOR FRANQUIA" ,
    label: "EMPREENDEDOR FRANQUIA" },
  { value: "EMPREGADA DOMESTICA / BABÁ / FAXINEIRA" ,
    label: "EMPREGADA DOMESTICA / BABÁ / FAXINEIRA" },
  { value: "EMPREITEIRO DE OBRAS" ,
    label: "EMPREITEIRO DE OBRAS" },
  { value: "EMPRESÁRIO (A) - COMBUSTÍVEIS" ,
    label: "EMPRESÁRIO (A) - COMBUSTÍVEIS" },
  { value: "EMPRESÁRIO (A) - ILUMINAÇÃO" ,
    label: "EMPRESÁRIO (A) - ILUMINAÇÃO" },
  { value: "EMPRESÁRIO (A) - INTERCÂMBIOS" ,
    label: "EMPRESÁRIO (A) - INTERCÂMBIOS" },
  { value: "EMPRESÁRIO (A) - ISOPOR" ,
    label: "EMPRESÁRIO (A) - ISOPOR" },
  { value: "EMPRESÁRIO (A) - MICROFIL.DIG" ,
    label: "EMPRESÁRIO (A) - MICROFIL.DIG" },
  { value: "EMPRESÁRIO - ARTIGOS DE COURO" ,
    label: "EMPRESÁRIO - ARTIGOS DE COURO" },
  { value: "EMPRESÁRIO - BRINDES PROMOC." ,
    label: "EMPRESÁRIO - BRINDES PROMOC." },
  { value: "EMPRESÁRIO - CONSTRUÇÃO CIVIL" ,
    label: "EMPRESÁRIO - CONSTRUÇÃO CIVIL" },
  { value: "EMPRESÁRIO - ESQ. METÁLICAS" ,
    label: "EMPRESÁRIO - ESQ. METÁLICAS" },
  { value: "EMPRESÁRIO - FACTORING" ,
    label: "EMPRESÁRIO - FACTORING" },
  { value: "EMPRESÁRIO - MADEIREIRA" ,
    label: "EMPRESÁRIO - MADEIREIRA" },
  { value: "EMPRESÁRIO - NAVIOS" ,
    label: "EMPRESÁRIO - NAVIOS" },
  { value: "EMPRESÁRIO - RAMO DE ARTES" ,
    label: "EMPRESÁRIO - RAMO DE ARTES" },
  { value: "EMPRESÁRIO - RAMO DE BLINDAGEM" ,
    label: "EMPRESÁRIO - RAMO DE BLINDAGEM" },
  { value: "EMPRESÁRIO - RAMO DE CALÇADOS" ,
    label: "EMPRESÁRIO - RAMO DE CALÇADOS" },
  { value: "EMPRESÁRIO - RAMO PLÁSTICOS" ,
    label: "EMPRESÁRIO - RAMO PLÁSTICOS" },
  { value: "EMPRESÁRIO - RAMO RESTAURANTES" ,
    label: "EMPRESÁRIO - RAMO RESTAURANTES" },
  { value: "EMPRESÁRIO - SALÃO DE BELEZA" ,
    label: "EMPRESÁRIO - SALÃO DE BELEZA" },
  { value: "EMPRESÁRIO - TELECOMUNICAÇÕES" ,
    label: "EMPRESÁRIO - TELECOMUNICAÇÕES" },
  { value: "EMPRESÁRIO(A)- IND.DE BOTOES" ,
    label: "EMPRESÁRIO(A)- IND.DE BOTOES" },
  { value: "EMPRESÁRIO-RAMO DE TURISMO" ,
    label: "EMPRESÁRIO-RAMO DE TURISMO" },
  { value: "EMPRESÁRIO-RAMO AR CONDICIONAD" ,
    label: "EMPRESÁRIO-RAMO AR CONDICIONAD" },
  { value: "EMPRESÁRIO-RAMO LAVANDERIA" ,
    label: "EMPRESÁRIO-RAMO LAVANDERIA" },
  { value: "EMPRES.PREST SERV VIGILANCIA PARTICULAR" ,
    label: "EMPRES.PREST SERV VIGILANCIA PARTICULAR" },
  { value: "EMPRESARIA - DONA DE CARTORIO" ,
    label: "EMPRESARIA - DONA DE CARTORIO" },
  { value: "EMPRESARIA - RAMO IMOVEIS" ,
    label: "EMPRESARIA - RAMO IMOVEIS" },
  { value: "EMPRESARIA LOJA DE ARTESANATO" ,
    label: "EMPRESARIA LOJA DE ARTESANATO" },
  { value: "EMPRESARIO" ,
    label: "EMPRESARIO" },
  { value: "EMPRESARIO  - MARMORARIA" ,
    label: "EMPRESARIO  - MARMORARIA" },
  { value: "EMPRESARIO  - RAMO HOTEL" ,
    label: "EMPRESARIO  - RAMO HOTEL" },
  { value: "EMPRESARIO  - VIDEO LOCADORA" ,
    label: "EMPRESARIO  - VIDEO LOCADORA" },
  { value: "EMPRESARIO ( A ) - RAMO TEXTIL" ,
    label: "EMPRESARIO ( A ) - RAMO TEXTIL" },
  { value: "EMPRESARIO (A)   ART P/ FESTAS" ,
    label: "EMPRESARIO (A)   ART P/ FESTAS" },
  { value: "EMPRESARIO (A) - ASSESSORIA" ,
    label: "EMPRESARIO (A) - ASSESSORIA" },
  { value: "EMPRESARIO (A) - DISTR. FILMES" ,
    label: "EMPRESARIO (A) - DISTR. FILMES" },
  { value: "EMPRESARIO (A) - ETIQ ADESIVAS" ,
    label: "EMPRESARIO (A) - ETIQ ADESIVAS" },
  { value: "EMPRESARIO (A) - PROD DE VIDEO" ,
    label: "EMPRESARIO (A) - PROD DE VIDEO" },
  { value: "EMPRESARIO (A) - RAMO DE SAÚDE" ,
    label: "EMPRESARIO (A) - RAMO DE SAÚDE" },
  { value: "EMPRESARIO (A) - TRANSPORTES" ,
    label: "EMPRESARIO (A) - TRANSPORTES" },
  { value: "EMPRESARIO (A) PRODS. QUIMICOS" ,
    label: "EMPRESARIO (A) PRODS. QUIMICOS" },
  { value: "EMPRESARIO (A) RAMO DE TECIDOS" ,
    label: "EMPRESARIO (A) RAMO DE TECIDOS" },
  { value: "EMPRESARIO (A) RAMO ENGENHARIA" ,
    label: "EMPRESARIO (A) RAMO ENGENHARIA" },
  { value: "EMPRESARIO - AUTO POSTO" ,
    label: "EMPRESARIO - AUTO POSTO" },
  { value: "EMPRESARIO - AVIOES" ,
    label: "EMPRESARIO - AVIOES" },
  { value: "EMPRESARIO - CASA DE CARNES" ,
    label: "EMPRESARIO - CASA DE CARNES" },
  { value: "EMPRESARIO - CASA NOTURNA" ,
    label: "EMPRESARIO - CASA NOTURNA" },
  { value: "EMPRESARIO - CLUBE RECREATIVO" ,
    label: "EMPRESARIO - CLUBE RECREATIVO" },
  { value: "EMPRESARIO - DONO CONSTRUTORA" ,
    label: "EMPRESARIO - DONO CONSTRUTORA" },
  { value: "EMPRESARIO - ENERGIA ELETRICA" ,
    label: "EMPRESARIO - ENERGIA ELETRICA" },
  { value: "EMPRESARIO - FABRICA CARIMBOS" ,
    label: "EMPRESARIO - FABRICA CARIMBOS" },
  { value: "EMPRESARIO - FABRICA PLASTICO" ,
    label: "EMPRESARIO - FABRICA PLASTICO" },
  { value: "EMPRESARIO - FUNERARIA" ,
    label: "EMPRESARIO - FUNERARIA" },
  { value: "EMPRESARIO - GRANJA" ,
    label: "EMPRESARIO - GRANJA" },
  { value: "EMPRESARIO - IMPLEM. AGRICOLAS" ,
    label: "EMPRESARIO - IMPLEM. AGRICOLAS" },
  { value: "EMPRESARIO - INST. DE ALARMES" ,
    label: "EMPRESARIO - INST. DE ALARMES" },
  { value: "EMPRESARIO - INSTR. MUSICAIS" ,
    label: "EMPRESARIO - INSTR. MUSICAIS" },
  { value: "EMPRESARIO - LJ. R$ 1,99" ,
    label: "EMPRESARIO - LJ. R$ 1,99" },
  { value: "EMPRESARIO - LOJA DE CELULAR" ,
    label: "EMPRESARIO - LOJA DE CELULAR" },
  { value: "EMPRESARIO - LOJA DE COLCHOES" ,
    label: "EMPRESARIO - LOJA DE COLCHOES" },
  { value: "EMPRESARIO - LOJA DE ROUPAS" ,
    label: "EMPRESARIO - LOJA DE ROUPAS" },
  { value: "EMPRESARIO - MOTEL" ,
    label: "EMPRESARIO - MOTEL" },
  { value: "EMPRESARIO - OFICINA MECANICA" ,
    label: "EMPRESARIO - OFICINA MECANICA" },
  { value: "EMPRESARIO - PAISAGISMO" ,
    label: "EMPRESARIO - PAISAGISMO" },
  { value: "EMPRESARIO - PET SHOP" ,
    label: "EMPRESARIO - PET SHOP" },
  { value: "EMPRESARIO - RAMO DE ACADEMIA" ,
    label: "EMPRESARIO - RAMO DE ACADEMIA" },
  { value: "EMPRESARIO - RAMO DE ADVOCACIA" ,
    label: "EMPRESARIO - RAMO DE ADVOCACIA" },
  { value: "EMPRESARIO - RAMO DE BORRACHAS" ,
    label: "EMPRESARIO - RAMO DE BORRACHAS" },
  { value: "EMPRESARIO - RAMO DE EVENTOS" ,
    label: "EMPRESARIO - RAMO DE EVENTOS" },
  { value: "EMPRESARIO - RAMO DE MAQUINAS" ,
    label: "EMPRESARIO - RAMO DE MAQUINAS" },
  { value: "EMPRESARIO - RAMO DE MOVEIS" ,
    label: "EMPRESARIO - RAMO DE MOVEIS" },
  { value: "EMPRESARIO - RAMO DE SEGUROS" ,
    label: "EMPRESARIO - RAMO DE SEGUROS" },
  { value: "EMPRESARIO - RAMO DE VIDROS" ,
    label: "EMPRESARIO - RAMO DE VIDROS" },
  { value: "EMPRESARIO - RAMO ALIMENTICIO" ,
    label: "EMPRESARIO - RAMO ALIMENTICIO" },
  { value: "EMPRESARIO - RAMO ALUMINIO" ,
    label: "EMPRESARIO - RAMO ALUMINIO" },
  { value: "EMPRESARIO - RAMO AUTO-PECAS" ,
    label: "EMPRESARIO - RAMO AUTO-PECAS" },
  { value: "EMPRESARIO - RAMO AUTOMOTOR" ,
    label: "EMPRESARIO - RAMO AUTOMOTOR" },
  { value: "EMPRESARIO - RAMO CERAMICA" ,
    label: "EMPRESARIO - RAMO CERAMICA" },
  { value: "EMPRESARIO - RAMO CONFECCAO" ,
    label: "EMPRESARIO - RAMO CONFECCAO" },
  { value: "EMPRESARIO - RAMO CONTABIL" ,
    label: "EMPRESARIO - RAMO CONTABIL" },
  { value: "EMPRESARIO - RAMO COPIADORA" ,
    label: "EMPRESARIO - RAMO COPIADORA" },
  { value: "EMPRESARIO - RAMO DECORACAO" ,
    label: "EMPRESARIO - RAMO DECORACAO" },
  { value: "EMPRESARIO - RAMO ESPORTES" ,
    label: "EMPRESARIO - RAMO ESPORTES" },
  { value: "EMPRESARIO - RAMO ESTETICA" ,
    label: "EMPRESARIO - RAMO ESTETICA" },
  { value: "EMPRESARIO - RAMO ESTOFARIA" ,
    label: "EMPRESARIO - RAMO ESTOFARIA" },
  { value: "EMPRESARIO - RAMO FOTOGRAFIA" ,
    label: "EMPRESARIO - RAMO FOTOGRAFIA" },
  { value: "EMPRESARIO - RAMO GRAFICA" ,
    label: "EMPRESARIO - RAMO GRAFICA" },
  { value: "EMPRESARIO - RAMO INFORMATICA" ,
    label: "EMPRESARIO - RAMO INFORMATICA" },
  { value: "EMPRESARIO - RAMO LIVRARIA" ,
    label: "EMPRESARIO - RAMO LIVRARIA" },
  { value: "EMPRESARIO - RAMO LOGISTICA" ,
    label: "EMPRESARIO - RAMO LOGISTICA" },
  { value: "EMPRESARIO - RAMO LOTERIA" ,
    label: "EMPRESARIO - RAMO LOTERIA" },
  { value: "EMPRESARIO - RAMO MARCENARIA" ,
    label: "EMPRESARIO - RAMO MARCENARIA" },
  { value: "EMPRESARIO - RAMO MOTOBOYS" ,
    label: "EMPRESARIO - RAMO MOTOBOYS" },
  { value: "EMPRESARIO - RAMO OTICA" ,
    label: "EMPRESARIO - RAMO OTICA" },
  { value: "EMPRESARIO - RAMO PADARIA" ,
    label: "EMPRESARIO - RAMO PADARIA" },
  { value: "EMPRESARIO - RAMO PALMILHAS" ,
    label: "EMPRESARIO - RAMO PALMILHAS" },
  { value: "EMPRESARIO - RAMO PIZZARIA" ,
    label: "EMPRESARIO - RAMO PIZZARIA" },
  { value: "EMPRESARIO - RAMO PUBLICIDADE" ,
    label: "EMPRESARIO - RAMO PUBLICIDADE" },
  { value: "EMPRESARIO - RAMO TELEFONIA" ,
    label: "EMPRESARIO - RAMO TELEFONIA" },
  { value: "EMPRESARIO - RAMO VIGILANCIA" ,
    label: "EMPRESARIO - RAMO VIGILANCIA" },
  { value: "EMPRESARIO - SERVICOS GERAIS" ,
    label: "EMPRESARIO - SERVICOS GERAIS" },
  { value: "EMPRESARIO APARELHO CIRURGICO" ,
    label: "EMPRESARIO APARELHO CIRURGICO" },
  { value: "EMPRESARIO COM PESCA E NAUTICA" ,
    label: "EMPRESARIO COM PESCA E NAUTICA" },
  { value: "EMPRESARIO COMUNICACAO VISUAL" ,
    label: "EMPRESARIO COMUNICACAO VISUAL" },
  { value: "EMPRESARIO ESTRS METALICAS" ,
    label: "EMPRESARIO ESTRS METALICAS" },
  { value: "EMPRESARIO HIDRO IRRIGACAO" ,
    label: "EMPRESARIO HIDRO IRRIGACAO" },
  { value: "EMPRESARIO IMPORT. EXPORTACAO" ,
    label: "EMPRESARIO IMPORT. EXPORTACAO" },
  { value: "EMPRESARIO IND. ENG.DE BEBIDAS" ,
    label: "EMPRESARIO IND. ENG.DE BEBIDAS" },
  { value: "EMPRESARIO MATERIAL CONSTRUCAO" ,
    label: "EMPRESARIO MATERIAL CONSTRUCAO" },
  { value: "EMPRESARIO PRES SERV MANUTENC." ,
    label: "EMPRESARIO PRES SERV MANUTENC." },
  { value: "EMPRESARIO PRODS AGROPECUÁRIOS" ,
    label: "EMPRESARIO PRODS AGROPECUÁRIOS" },
  { value: "EMPRESARIO PRODUTO HOSPITALAR" ,
    label: "EMPRESARIO PRODUTO HOSPITALAR" },
  { value: "EMPRESARIO RAMO DE BRINQUEDOS" ,
    label: "EMPRESARIO RAMO DE BRINQUEDOS" },
  { value: "EMPRESARIO RAMO DE COSMETICOS" ,
    label: "EMPRESARIO RAMO DE COSMETICOS" },
  { value: "EMPRESARIO RAMO DE FARMACIA" ,
    label: "EMPRESARIO RAMO DE FARMACIA" },
  { value: "EMPRESARIO RAMO COBRANCA",
    label: "EMPRESARIO RAMO COBRANCA", 
  },
  { value: "EMPRESARIO RAMO CONCESSIONARIA",
    label: "EMPRESARIO RAMO CONCESSIONARIA"
  },
  { 
      value: "EMPRESARIO RAMO CONSULTORIA",
      label: "EMPRESARIO RAMO CONSULTORIA" 
    },
  {   value: "EMPRESARIO RAMO IMOBILIARIA",
      label: "EMPRESARIO RAMO IMOBILIARIA" },
  { value: "EMPRESARIO RAMO MINERACAO" ,
    label: "EMPRESARIO RAMO MINERACAO" },
  { value: "EMPRESARIO RAMO SOFTWARE" ,
    label: "EMPRESARIO RAMO SOFTWARE" },
  { value: "EMPRESARIO RAMO TERRAPLANAGEM" ,
    label: "EMPRESARIO RAMO TERRAPLANAGEM" },
  { value: "EMPRESARIO RURAL" ,
    label: "EMPRESARIO RURAL" },
  { value: "EMPRESARIO SANEAMENTO E SERVS." ,
    label: "EMPRESARIO SANEAMENTO E SERVS." },
  { value: "EMPRESARIO(A) - ESTACIONAMENTO" ,
    label: "EMPRESARIO(A) - ESTACIONAMENTO" },
  { value: "EMPRESARIO(A) - FRIGORIFICO" ,
    label: "EMPRESARIO(A) - FRIGORIFICO" },
  { value: "EMPRESARIO(A) - LOJA DE JOIAS" ,
    label: "EMPRESARIO(A) - LOJA DE JOIAS" },
  { value: "EMPRESARIO(A) - METALURGICA" ,
    label: "EMPRESARIO(A) - METALURGICA" },
  { value: "EMPRESARIO(A) - RAMO ESCOLA" ,
    label: "EMPRESARIO(A) - RAMO ESCOLA" },
  { value: "EMPRESARIO(A) MANUT. INDUSTR." ,
    label: "EMPRESARIO(A) MANUT. INDUSTR." },
  { value: "EMPRESARIO-AGENCIA DE VIAGENS" ,
    label: "EMPRESARIO-AGENCIA DE VIAGENS" },
  { value: "EMPRESARIO-PARQUE DE DIVERSÕES" ,
    label: "EMPRESARIO-PARQUE DE DIVERSÕES" },
  { value: "EMPRESARIO-RAMO DE BEBIDAS" ,
    label: "EMPRESARIO-RAMO DE BEBIDAS" },
  { value: "EMPRESARIO-RAMO DE MAGAZINE" ,
    label: "EMPRESARIO-RAMO DE MAGAZINE" },
  { value: "EMPRESARIO-RAMO DE MAGAZINE" ,
    label: "EMPRESARIO-RAMO DE MAGAZINE" },
  { value: "EMPRESARIO-RAMO HIPERMERCADO" ,
    label: "EMPRESARIO-RAMO HIPERMERCADO" },
  { value: "EMPRESARIO-SERVICOS MARITIMOS" ,
    label: "EMPRESARIO-SERVICOS MARITIMOS" },
  { value: "ENCADERNADOR" ,
    label: "ENCADERNADOR" },
  { value: "ENCARREGADO (A ) FINANCEIRO (A" ,
    label: "ENCARREGADO (A ) FINANCEIRO (A" },
  { value: "ENCARREGADO DE COBRANCA" ,
    label: "ENCARREGADO DE COBRANCA" },
  { value: "ENCARREGADO DE DEPÓSITO" ,
    label: "ENCARREGADO DE DEPÓSITO" },
  { value: "ENCARREGADO DE MANUTENCAO" ,
    label: "ENCARREGADO DE MANUTENCAO" },
  { value: "ENCARREGADO DE OBRAS" ,
    label: "ENCARREGADO DE OBRAS" },
  { value: "ENCARREGADO DE PRODUCAO" ,
    label: "ENCARREGADO DE PRODUCAO" },
  { value: "ENCARREGADO DE TRANSPORTES" ,
    label: "ENCARREGADO DE TRANSPORTES" },
  { value: "ENCARREGADO DE USINAGEM" ,
    label: "ENCARREGADO DE USINAGEM" },
  { value: "ENCARREGADO DEPTO PESSOAL" ,
    label: "ENCARREGADO DEPTO PESSOAL" },
  { value: "ENFERMEIRO" ,
    label: "ENFERMEIRO" },
  { value: "ENGENHEIRO" ,
    label: "ENGENHEIRO" },
  { value: "ENGENHEIRO - RAMO PETROLEO" ,
    label: "ENGENHEIRO - RAMO PETROLEO" },
  { value: "ENGENHEIRO DE PRODUCAO" ,
    label: "ENGENHEIRO DE PRODUCAO" },
  { value: "ENGENHEIRO DE REDES" ,
    label: "ENGENHEIRO DE REDES" },
  { value: "ENGENHEIRO DE SISTEMAS" ,
    label: "ENGENHEIRO DE SISTEMAS" },
  { value: "ENGENHEIRO DE SOFTWARE" ,
    label: "ENGENHEIRO DE SOFTWARE" },
  { value: "ENGENHEIRO AGRONOMO" ,
    label: "ENGENHEIRO AGRONOMO" },
  { value: "ENGENHEIRO CARTOGRAFO" ,
    label: "ENGENHEIRO CARTOGRAFO" },
  { value: "ENGENHEIRO CIVIL" ,
    label: "ENGENHEIRO CIVIL" },
  { value: "ENGENHEIRO ELETRICO" ,
    label: "ENGENHEIRO ELETRICO" },
  { value: "ENGENHEIRO ELETRONICO" ,
    label: "ENGENHEIRO ELETRONICO" },
  { value: "ENGENHEIRO INDUSTRIAL" ,
    label: "ENGENHEIRO INDUSTRIAL" },
  { value: "ENGENHEIRO MECANICO" ,
    label: "ENGENHEIRO MECANICO" },
  { value: "ENGENHEIRO METALURGICO" ,
    label: "ENGENHEIRO METALURGICO" },
  { value: "ENGENHEIRO NAVAL" ,
    label: "ENGENHEIRO NAVAL" },
  { value: "ENGENHEIRO PLENO" ,
    label: "ENGENHEIRO PLENO" },
  { value: "ENGENHEIRO QUIMICO" ,
    label: "ENGENHEIRO QUIMICO" },
  { value: "ENGENHEIRO(A) ELETRICISTA" ,
    label: "ENGENHEIRO(A) ELETRICISTA" },
  { value: "ENGENHEIRO(A) MECANICO(A) TEXT" ,
    label: "ENGENHEIRO(A) MECANICO(A) TEXT" },
  { value: "ENOLOGO" ,
    label: "ENOLOGO" },
  { value: "ENTREGADOR" ,
    label: "ENTREGADOR" },
  { value: "ESCREVENTE" ,
    label: "ESCREVENTE" },
  { value: "ESCRITOR" ,
    label: "ESCRITOR" },
  { value: "ESCRITURARIO" ,
    label: "ESCRITURARIO" },
  { value: "ESCRIVÃO" ,
    label: "ESCRIVÃO" },
  { value: "ESCULTOR" ,
    label: "ESCULTOR" },
  { value: "ESTAGIARIO" ,
    label: "ESTAGIARIO" },
  { value: "ESTATÍSTICO" ,
    label: "ESTATÍSTICO" },
  { value: "ESTETICISTA" ,
    label: "ESTETICISTA" },
  { value: "ESTETICISTA" ,
    label: "ESTETICISTA" },
  { value: "ESTILISTA" ,
    label: "ESTILISTA" },
  { value: "ESTIVADOR" ,
    label: "ESTIVADOR" },
  { value: "ESTOQUISTA" ,
    label: "ESTOQUISTA" },
  { value: "ESTUDANTE" ,
    label: "ESTUDANTE" },
  { value: "FARMACEUTICO" ,
    label: "FARMACEUTICO" },
  { value: "FATURISTA" ,
    label: "FATURISTA" },
  { value: "FAXINEIRO" ,
    label: "FAXINEIRO" },
  { value: "FAZENDEIRO" ,
    label: "FAZENDEIRO" },
  { value: "FEIRANTE" ,
    label: "FEIRANTE" },
  { value: "FERRAMENTEIRO" ,
    label: "FERRAMENTEIRO" },
  { value: "FERROVIARIO" ,
    label: "FERROVIARIO" },
  { value: "FISCAL DE LOJA" ,
    label: "FISCAL DE LOJA" },
  { value: "FISCAL DE RENDA" ,
    label: "FISCAL DE RENDA" },
  { value: "FISCAL DE TRANSPORTES" ,
    label: "FISCAL DE TRANSPORTES" },
  { value: "FISCAL DE TRIBUTOS" ,
    label: "FISCAL DE TRIBUTOS" },
  { value: "FISICO" ,
    label: "FISICO" },
  { value: "FISIOTERAPEUTA" ,
    label: "FISIOTERAPEUTA" },
  { value: "FLORICULTOR" ,
    label: "FLORICULTOR" },
  { value: "FONOAUDIOLOGO" ,
    label: "FONOAUDIOLOGO" },
  { value: "FOTOGRAFO" ,
    label: "FOTOGRAFO" },
  { value: "FRENTISTA" ,
    label: "FRENTISTA" },
  { value: "FREZADOR" ,
    label: "FREZADOR" },
  { value: "FUNCIONARIO PUBLICO" ,
    label: "FUNCIONARIO PUBLICO" },
  { value: "FUNDIDOR" ,
    label: "FUNDIDOR" },
  { value: "FUNILEIRO" ,
    label: "FUNILEIRO" },
  { value: "FURADOR RADIAL" ,
    label: "FURADOR RADIAL" },
  { value: "GARCOM" ,
    label: "GARCOM" },
  { value: "GARIMPEIRO" ,
    label: "GARIMPEIRO" },
  { value: "GEOGRAFO" ,
    label: "GEOGRAFO" },
  { value: "GEOLOGO" ,
    label: "GEOLOGO" },
  { value: "GERENTE - AGENCIA BANCÁRIA" ,
    label: "GERENTE - AGENCIA BANCÁRIA" },
  { value: "GERENTE DE ASSISTÊNCIA TÉCNICA" ,
    label: "GERENTE DE ASSISTÊNCIA TÉCNICA" },
  { value: "GERENTE DE CARGAS" ,
    label: "GERENTE DE CARGAS" },
  { value: "GERENTE DE COBRANÇA" ,
    label: "GERENTE DE COBRANÇA" },
  { value: "GERENTE DE CONDOMINIO" ,
    label: "GERENTE DE CONDOMINIO" },
  { value: "GERENTE DE CONTAS" ,
    label: "GERENTE DE CONTAS" },
  { value: "GERENTE DE EXPEDICAO" ,
    label: "GERENTE DE EXPEDICAO" },
  { value: "GERENTE DE EXPORTACAO CALCADOS" ,
    label: "GERENTE DE EXPORTACAO CALCADOS" },
  { value: "GERENTE DE LOGISTICA" ,
    label: "GERENTE DE LOGISTICA" },
  { value: "GERENTE DE LOJA" ,
    label: "GERENTE DE LOJA" },
  { value: "GERENTE DE MODA" ,
    label: "GERENTE DE MODA" },
  { value: "GERENTE DE OFICINA MECÂNICA" ,
    label: "GERENTE DE OFICINA MECÂNICA" },
  { value: "GERENTE DE PROC. DE DADOS" ,
    label: "GERENTE DE PROC. DE DADOS" },
  { value: "GERENTE DE PRODUÇÃO" ,
    label: "GERENTE DE PRODUÇÃO" },
  { value: "GERENTE DE PRODUTOS" ,
    label: "GERENTE DE PRODUTOS" },
  { value: "GERENTE DE PROJETOS" ,
    label: "GERENTE DE PROJETOS" },
  { value: "GERENTE DE RECURSOS HUMANOS" ,
    label: "GERENTE DE RECURSOS HUMANOS" },
  { value: "GERENTE DE RESTAURANTE" ,
    label: "GERENTE DE RESTAURANTE" },
  { value: "GERENTE DE SUPORTE TECNICO" ,
    label: "GERENTE DE SUPORTE TECNICO" },
  { value: "GERENTE DE VENDAS" ,
    label: "GERENTE DE VENDAS" },
  { value: "GERENTE COMERCIAL" ,
    label: "GERENTE COMERCIAL" },
  { value: "GERENTE CUSTO/ORCAMENTO" ,
    label: "GERENTE CUSTO/ORCAMENTO" },
  { value: "GERENTE FINANCEIRO" ,
    label: "GERENTE FINANCEIRO" },
  { value: "GERENTE FISCAL" ,
    label: "GERENTE FISCAL" },
  { value: "GERENTE INDUSTRIAL" ,
    label: "GERENTE INDUSTRIAL" },
  { value: "GERENTE MARKETING" ,
    label: "GERENTE MARKETING" },
  { value: "GERENTE TELECOMUNICACOES" ,
    label: "GERENTE TELECOMUNICACOES" },
  { value: "GERENTE TERRITORIO" ,
    label: "GERENTE TERRITORIO" },
  { value: "GESSEIRO" ,
    label: "GESSEIRO" },
  { value: "GEÔMETRA" ,
    label: "GEÔMETRA" },
  { value: "GOVERNANTA" ,
    label: "GOVERNANTA" },
  { value: "GRAFICO" ,
    label: "GRAFICO" },
  { value: "GUARDA" ,
    label: "GUARDA" },
  { value: "GUARDA MUNICIPAL" ,
    label: "GUARDA MUNICIPAL" },
  { value: "GUIA TURISTICO" ,
    label: "GUIA TURISTICO" },
  { value: "ILUMINOTECNICO" ,
    label: "ILUMINOTECNICO" },
  { value: "IMPRESSOR GRAFICO" ,
    label: "IMPRESSOR GRAFICO" },
  { value: "INDUSTRIAL" ,
    label: "INDUSTRIAL" },
  { value: "INDUSTRIAL DE CALCADOS" ,
    label: "INDUSTRIAL DE CALCADOS" },
  { value: "INDUSTRIARIO" ,
    label: "INDUSTRIARIO" },
  { value: "INDUSTRIARIO RAMO REFINARIA" ,
    label: "INDUSTRIARIO RAMO REFINARIA" },
  { value: "INSPETOR DE ALUNOS" ,
    label: "INSPETOR DE ALUNOS" },
  { value: "INSPETOR DE LABORATORIO" ,
    label: "INSPETOR DE LABORATORIO" },
  { value: "INSPETOR DE RECEBIMENTOS" ,
    label: "INSPETOR DE RECEBIMENTOS" },
  { value: "INSPETOR DE SEGURANCA" ,
    label: "INSPETOR DE SEGURANCA" },
  { value: "INSPETOR ADMINISTRATIVO" ,
    label: "INSPETOR ADMINISTRATIVO" },
  { value: "INSPETOR CONTROLE DE QUALIDADE" ,
    label: "INSPETOR CONTROLE DE QUALIDADE" },
  { value: "INSPETOR RAMO TRANSPORTES" ,
    label: "INSPETOR RAMO TRANSPORTES" },
  { value: "INSPETOR TECNICO" ,
    label: "INSPETOR TECNICO" },
  { value: "INSTALADOR DE ANTENA" ,
    label: "INSTALADOR DE ANTENA" },
  { value: "INSTALADOR DE BOX" ,
    label: "INSTALADOR DE BOX" },
  { value: "INSTALADOR DE CALHAS" ,
    label: "INSTALADOR DE CALHAS" },
  { value: "INSTALADOR DE PAINEIS" ,
    label: "INSTALADOR DE PAINEIS" },
  { value: "INSTALADOR DE PERSIANAS" ,
    label: "INSTALADOR DE PERSIANAS" },
  { value: "INSTRUMENTADOR(A)  CIRURGICO(A)" ,
    label: "INSTRUMENTADOR(A)  CIRURGICO(A)" },
  { value: "INSTRUTOR" ,
    label: "INSTRUTOR" },
  { value: "INSTRUTOR DE AUTO ESCOLA" ,
    label: "INSTRUTOR DE AUTO ESCOLA" },
  { value: "INSTRUTOR DE BASQUETE" ,
    label: "INSTRUTOR DE BASQUETE" },
  { value: "INSTRUTOR DE JUDO" ,
    label: "INSTRUTOR DE JUDO" },
  { value: "INSTRUTOR DE TENIS" ,
    label: "INSTRUTOR DE TENIS" },
  { value: "INSTRUTOR DE VOLEI" ,
    label: "INSTRUTOR DE VOLEI" },
  { value: "INVESTIGADOR DE POLICIA" ,
    label: "INVESTIGADOR DE POLICIA" },
  { value: "JARDINEIRO" ,
    label: "JARDINEIRO" },
  { value: "JOALHEIRO" ,
    label: "JOALHEIRO" },
  { value: "JOCKEY" ,
    label: "JOCKEY" },
  { value: "JOGADOR DE FUTEBOL" ,
    label: "JOGADOR DE FUTEBOL" },
  { value: "JORNALEIRO" ,
    label: "JORNALEIRO" },
  { value: "JORNALISTA" ,
    label: "JORNALISTA" },
  { value: "JUIZ DE DIREITO" ,
    label: "JUIZ DE DIREITO" },
  { value: "LANTERNEIRO" ,
    label: "LANTERNEIRO" },
  { value: "LAVADOR DE AUTOMOVEIS" ,
    label: "LAVADOR DE AUTOMOVEIS" },
  { value: "LELOEIRO" ,
    label: "LELOEIRO" },
  { value: "LIDER DE CONTROLE DE QUALIDADE" ,
    label: "LIDER DE CONTROLE DE QUALIDADE" },
  { value: "LIDER DE MONTAGEM" ,
    label: "LIDER DE MONTAGEM" },
  { value: "LOCUTOR" ,
    label: "LOCUTOR" },
  { value: "LUTHIER" ,
    label: "LUTHIER" },
  { value: "MAGISTRADO" ,
    label: "MAGISTRADO" },
  { value: "MAGISTRADO FEDERAL" ,
    label: "MAGISTRADO FEDERAL" },
  { value: "MAITRE" ,
    label: "MAITRE" },
  { value: "MANDRILHADOR" ,
    label: "MANDRILHADOR" },
  { value: "MANICURE / PEDICURE / PODOLOGO /" ,
    label: "MANICURE / PEDICURE / PODOLOGO /" },
  { value: "MANOBRISTA" ,
    label: "MANOBRISTA" },
  { value: "MAQUIADORA" ,
    label: "MAQUIADORA" },
  { value: "MARCENEIRO" ,
    label: "MARCENEIRO" },
  { value: "MARCHAND" ,
    label: "MARCHAND" },
  { value: "MARINHEIRO" ,
    label: "MARINHEIRO" },
  { value: "MARKETING PROMOCIONAL" ,
    label: "MARKETING PROMOCIONAL" },
  { value: "MARMORISTA" ,
    label: "MARMORISTA" },
  { value: "MARQUETOLOGA" ,
    label: "MARQUETOLOGA" },
  { value: "MASSAGISTA" ,
    label: "MASSAGISTA" },
  { value: "MASSOTERAPEUTA" ,
    label: "MASSOTERAPEUTA" },
  { value: "MATEMATICO" ,
    label: "MATEMATICO" },
  { value: "MECANICO" ,
    label: "MECANICO" },
  { value: "MECANICO DE MANUTENCAO" ,
    label: "MECANICO DE MANUTENCAO" },
  { value: "MECANICO DIESEL" ,
    label: "MECANICO DIESEL" },
  { value: "MEDICO" ,
    label: "MEDICO" },
  { value: "MEDICO (A) ANESTESISTA" ,
    label: "MEDICO (A) ANESTESISTA" },
  { value: "MEDICO(A) OFTALMOLOGISTA" ,
    label: "MEDICO(A) OFTALMOLOGISTA" },
  { value: "MEDICO(A) RADIOLOGISTA" ,
    label: "MEDICO(A) RADIOLOGISTA" },
  { value: "MENSAGEIRO" ,
    label: "MENSAGEIRO" },
  { value: "MERCADÓLOGO" ,
    label: "MERCADÓLOGO" },
  { value: "MESTRE DE OBRAS" ,
    label: "MESTRE DE OBRAS" },
  { value: "METALURGICO" ,
    label: "METALURGICO" },
  { value: "METEOROLOGISTA" ,
    label: "METEOROLOGISTA" },
  { value: "METROVIÁRIO" ,
    label: "METROVIÁRIO" },
  { value: "METROVIÁRIO - BILHETERIA" ,
    label: "METROVIÁRIO - BILHETERIA" },
  { value: "MICRO EMPRESARIO" ,
    label: "MICRO EMPRESARIO" },
  { value: "MICRO-EMPRES AUTOM. INDUSTRIAL" ,
    label: "MICRO-EMPRES AUTOM. INDUSTRIAL" },
  { value: "MICRO-EMPRESARIO ESC. INFANTIL" ,
    label: "MICRO-EMPRESARIO ESC. INFANTIL" },
  { value: "MILITAR" ,
    label: "MILITAR" },
  { value: "MODELISTA" ,
    label: "MODELISTA" },
  { value: "MODELISTA DE CALCADOS" ,
    label: "MODELISTA DE CALCADOS" },
  { value: "MODELO / MANEQUIM" ,
    label: "MODELO / MANEQUIM" },
  { value: "MONITORA DE CRECHES" ,
    label: "MONITORA DE CRECHES" },
  { value: "MONTADOR DE ESTEIRAS" ,
    label: "MONTADOR DE ESTEIRAS" },
  { value: "MONTADOR DE FOTOLITO" ,
    label: "MONTADOR DE FOTOLITO" },
  { value: "MORDOMO" ,
    label: "MORDOMO" },
  { value: "MOTOBOY" ,
    label: "MOTOBOY" },
  { value: "MOTORISTA" ,
    label: "MOTORISTA" },
  { value: "MUSEOLOGA" ,
    label: "MUSEOLOGA" },
  { value: "MUSICO" ,
    label: "MUSICO" },
  { value: "NIVELADOR" ,
    label: "NIVELADOR" },
  { value: "NUTRICIONISTA" ,
    label: "NUTRICIONISTA" },
  { value: "ODONTOLOGO" ,
    label: "ODONTOLOGO" },
  { value: "OFFICE BOY" ,
    label: "OFFICE BOY" },
  { value: "OFICIAL DA MARINHA" ,
    label: "OFICIAL DA MARINHA" },
  { value: "OFICIAL DE JUSTICA" ,
    label: "OFICIAL DE JUSTICA" },
  { value: "OPERADOR (A) BOLSA DE VALORES" ,
    label: "OPERADOR (A) BOLSA DE VALORES" },
  { value: "OPERADOR DE ARMAZEM" ,
    label: "OPERADOR DE ARMAZEM" },
  { value: "OPERADOR DE AUDIO" ,
    label: "OPERADOR DE AUDIO" },
  { value: "OPERADOR DE BOMBEAMENTO" ,
    label: "OPERADOR DE BOMBEAMENTO" },
  { value: "OPERADOR DE CAIXA" ,
    label: "OPERADOR DE CAIXA" },
  { value: "OPERADOR DE ESCAVADEIRA" ,
    label: "OPERADOR DE ESCAVADEIRA" },
  { value: "OPERADOR DE MAQUINAS" ,
    label: "OPERADOR DE MAQUINAS" },
  { value: "OPERADOR DE MONTAGEM" ,
    label: "OPERADOR DE MONTAGEM" },
  { value: "OPERADOR DE OPEN" ,
    label: "OPERADOR DE OPEN" },
  { value: "OPERADOR DE PLANTA QUIMICA" ,
    label: "OPERADOR DE PLANTA QUIMICA" },
  { value: "OPERADOR DE PROCESSAMENTO" ,
    label: "OPERADOR DE PROCESSAMENTO" },
  { value: "OPERADOR DE SISTEMAS" ,
    label: "OPERADOR DE SISTEMAS" },
  { value: "OPERADOR DE TELECOMUNICAÇÕES" ,
    label: "OPERADOR DE TELECOMUNICAÇÕES" },
  { value: "OPERADOR DE TELEMARKETING" ,
    label: "OPERADOR DE TELEMARKETING" },
  { value: "OPERADOR DE VALORES" ,
    label: "OPERADOR DE VALORES" },
  { value: "OPERADOR COMERCIAL" ,
    label: "OPERADOR COMERCIAL" },
  { value: "OPERADOR FINANCEIRO" ,
    label: "OPERADOR FINANCEIRO" },
  { value: "OPERADOR INDUSTRIAL" ,
    label: "OPERADOR INDUSTRIAL" },
  { value: "OPERADOR PORTUARIO" ,
    label: "OPERADOR PORTUARIO" },
  { value: "OPERARIO" ,
    label: "OPERARIO" },
  { value: "OPTICO" ,
    label: "OPTICO" },
  { value: "ORIENTADORA EDUCACIONAL" ,
    label: "ORIENTADORA EDUCACIONAL" },
  { value: "ORIENTADORA PEDAGOGICA" ,
    label: "ORIENTADORA PEDAGOGICA" },
  { value: "ORTODONTISTA" ,
    label: "ORTODONTISTA" },
  { value: "OURIVES" ,
    label: "OURIVES" },
  { value: "PADEIRO" ,
    label: "PADEIRO" },
  { value: "PADRE / FREIRA / PASTOR" ,
    label: "PADRE / FREIRA / PASTOR" },
  { value: "PAISAGISTA" ,
    label: "PAISAGISTA" },
  { value: "PECUARISTA" ,
    label: "PECUARISTA" },
  { value: "PEDAGOGO (A)" ,
    label: "PEDAGOGO (A)" },
  { value: "PEDREIRO" ,
    label: "PEDREIRO" },
  { value: "PENSIONISTA" ,
    label: "PENSIONISTA" },
  { value: "PERFUSIONISTA" ,
    label: "PERFUSIONISTA" },
  { value: "PERITO" ,
    label: "PERITO" },
  { value: "PERITO JUDICIAL" ,
    label: "PERITO JUDICIAL" },
  { value: "PERITO(A) CRIMINAL" ,
    label: "PERITO(A) CRIMINAL" },
  { value: "PERSONAL TRAINER" ,
    label: "PERSONAL TRAINER" },
  { value: "PESCADOR (A)" ,
    label: "PESCADOR (A)" },
  { value: "PESPONTADOR DE CALCADOS" ,
    label: "PESPONTADOR DE CALCADOS" },
  { value: "PESQUISADOR" ,
    label: "PESQUISADOR" },
  { value: "PESQUISADOR DE MERCADO" ,
    label: "PESQUISADOR DE MERCADO" },
  { value: "PESQUISADORA IPT" ,
    label: "PESQUISADORA IPT" },
  { value: "PET SHOP" ,
    label: "PET SHOP" },
  { value: "PILOTO" ,
    label: "PILOTO" },
  { value: "PILOTO DE EMBARCAÇÕES" ,
    label: "PILOTO DE EMBARCAÇÕES" },
  { value: "PILOTO AERONAVES/ NÃO REGULAR" ,
    label: "PILOTO AERONAVES/ NÃO REGULAR" },
  { value: "PILOTO AERONAVES/LINHA REGULAR" ,
    label: "PILOTO AERONAVES/LINHA REGULAR" },
  { value: "PINTOR" ,
    label: "PINTOR" },
  { value: "PISCICULTOR" ,
    label: "PISCICULTOR" },
  { value: "PODOLOGO" ,
    label: "PODOLOGO" },
  { value: "POLICIAL" ,
    label: "POLICIAL" },
  { value: "PORTEIRO" ,
    label: "PORTEIRO" },
  { value: "PORTUARIO" ,
    label: "PORTUARIO" },
  { value: "PRATICO" ,
    label: "PRATICO" },
  { value: "PREFEITO" ,
    label: "PREFEITO" },
  { value: "PRESIDENTE" ,
    label: "PRESIDENTE" },
  { value: "PRODUTOR DE EVENTOS" ,
    label: "PRODUTOR DE EVENTOS" },
  { value: "PRODUTOR DE FLORES" ,
    label: "PRODUTOR DE FLORES" },
  { value: "PRODUTOR RURAL PAISAGISMO" ,
    label: "PRODUTOR RURAL PAISAGISMO" },
  { value: "PROFESSOR" ,
    label: "PROFESSOR" },
  { value: "PROGRAMADOR DE PRODUCAO" ,
    label: "PROGRAMADOR DE PRODUCAO" },
  { value: "PROGRAMADOR DE SISTEMAS" ,
    label: "PROGRAMADOR DE SISTEMAS" },
  { value: "PROGRAMADOR VISUAL" ,
    label: "PROGRAMADOR VISUAL" },
  { value: "PROJETISTA" ,
    label: "PROJETISTA" },
  { value: "PROMOTOR DE JUSTICA" ,
    label: "PROMOTOR DE JUSTICA" },
  { value: "PROMOTOR DE VENDAS" ,
    label: "PROMOTOR DE VENDAS" },
  { value: "PROPAGANDISTA" ,
    label: "PROPAGANDISTA" },
  { value: "PROTETICO" ,
    label: "PROTETICO" },
  { value: "PSICOLOGO" ,
    label: "PSICOLOGO" },
  { value: "PSICOTERAPEUTA" ,
    label: "PSICOTERAPEUTA" },
  { value: "PSIQUIATRA" ,
    label: "PSIQUIATRA" },
  { value: "PUBLICITARIO" ,
    label: "PUBLICITARIO" },
  { value: "QUIMICO" ,
    label: "QUIMICO" },
  { value: "RADIALISTA" ,
    label: "RADIALISTA" },
  { value: "RECEPCIONISTA" ,
    label: "RECEPCIONISTA" },
  { value: "REDATOR" ,
    label: "REDATOR" },
  { value: "REITORIA ADMINISTRATIVA" ,
    label: "REITORIA ADMINISTRATIVA" },
  { value: "RELACOES PUBLICAS" ,
    label: "RELACOES PUBLICAS" },
  { value: "REPORTER FOTOGRÁFICO" ,
    label: "REPORTER FOTOGRÁFICO" },
  { value: "REPR. VENDAS - SUPERMERCADO" ,
    label: "REPR. VENDAS - SUPERMERCADO" },
  { value: "REPRESENTANTE COMERCIAL" ,
    label: "REPRESENTANTE COMERCIAL" },
  { value: "REVISORA" ,
    label: "REVISORA" },
  { value: "RITILINISTA" ,
    label: "RITILINISTA" },
  { value: "ROTEIRISTA DE TV" ,
    label: "ROTEIRISTA DE TV" },
  { value: "SAPATEIRO" ,
    label: "SAPATEIRO" },
  { value: "SARRAFEIRO" ,
    label: "SARRAFEIRO" },
  { value: "SECRETARIA DA DIRETORIA" ,
    label: "SECRETARIA DA DIRETORIA" },
  { value: "SECRETARIA COMPRA  METALURGICA" ,
    label: "SECRETARIA COMPRA  METALURGICA" },
  { value: "SECRETARIO ( A )" ,
    label: "SECRETARIO ( A )" },
  { value: "SECURITARIO" ,
    label: "SECURITARIO" },
  { value: "SEGURANCA" ,
    label: "SEGURANCA" },
  { value: "SEPARADOR DE PECAS DE AUTO" ,
    label: "SEPARADOR DE PECAS DE AUTO" },
  { value: "SERRALHEIRO" ,
    label: "SERRALHEIRO" },
  { value: "SERVENTE" ,
    label: "SERVENTE" },
  { value: "SERVENTUARIO" ,
    label: "SERVENTUARIO" },
  { value: "SERVIDOR (A) DA JUSTICA" ,
    label: "SERVIDOR (A) DA JUSTICA" },
  { value: "SERVIDOR PUBL. FED." ,
    label: "SERVIDOR PUBL. FED." },
  { value: "SEXADOR DE ANIMAIS EM GRANJA" ,
    label: "SEXADOR DE ANIMAIS EM GRANJA" },
  { value: "SIDERÚRGICO" ,
    label: "SIDERÚRGICO" },
  { value: "SOCIOLOGO" ,
    label: "SOCIOLOGO" },
  { value: "SOLDADOR" ,
    label: "SOLDADOR" },
  { value: "SUINOCULTOR" ,
    label: "SUINOCULTOR" },
  { value: "SUPERINTENDENTE" ,
    label: "SUPERINTENDENTE" },
  { value: "SUPERVISOR" ,
    label: "SUPERVISOR" },
  { value: "SUPERVISOR  OPERACOES PETROLEO" ,
    label: "SUPERVISOR  OPERACOES PETROLEO" },
  { value: "SUPERVISOR  RAMO TRANSPORTES" ,
    label: "SUPERVISOR  RAMO TRANSPORTES" },
  { value: "SUPERVISOR DE COMPRAS" ,
    label: "SUPERVISOR DE COMPRAS" },
  { value: "SUPERVISOR DE CONTAS A PAGAR" ,
    label: "SUPERVISOR DE CONTAS A PAGAR" },
  { value: "SUPERVISOR DE EXP. AUTO PEÇAS" ,
    label: "SUPERVISOR DE EXP. AUTO PEÇAS" },
  { value: "SUPERVISOR DE MANUTENCAO" ,
    label: "SUPERVISOR DE MANUTENCAO" },
  { value: "SUPERVISOR DE PRODUCAO" ,
    label: "SUPERVISOR DE PRODUCAO" },
  { value: "SUPERVISOR DE PROJETOS" ,
    label: "SUPERVISOR DE PROJETOS" },
  { value: "SUPERVISOR DE SUPRIMENTOS" ,
    label: "SUPERVISOR DE SUPRIMENTOS" },
  { value: "SUPERVISOR DE TREINAMENTO" ,
    label: "SUPERVISOR DE TREINAMENTO" },
  { value: "SUPERVISOR DE VENDAS" ,
    label: "SUPERVISOR DE VENDAS" },
  { value: "SUPERVISOR DE VIGILANTE" ,
    label: "SUPERVISOR DE VIGILANTE" },
  { value: "SUPERVISOR ADMINISTRATIVO" ,
    label: "SUPERVISOR ADMINISTRATIVO" },
  { value: "SUPERVISOR SERV. MECANICOS" ,
    label: "SUPERVISOR SERV. MECANICOS" },
  { value: "TÉCNICO EM AÇÚCAR E ÁLCOOL" ,
    label: "TÉCNICO EM AÇÚCAR E ÁLCOOL" },
  { value: "TÉCNICO EM COUROS E CALÇADOS" ,
    label: "TÉCNICO EM COUROS E CALÇADOS" },
  { value: "TÉCNICO AMBIENTAL" ,
    label: "TÉCNICO AMBIENTAL" },
  { value: "TÉCNICO ESTETICISTA" ,
    label: "TÉCNICO ESTETICISTA" },
  { value: "TABELIAO" ,
    label: "TABELIAO" },
  { value: "TATUADOR" ,
    label: "TATUADOR" },
  { value: "TAXISTA" ,
    label: "TAXISTA" },
  { value: "TECNICA EM COMPUTACAO" ,
    label: "TECNICA EM COMPUTACAO" },
  { value: "TECNICA EM NUTRICAO" ,
    label: "TECNICA EM NUTRICAO" },
  { value: "TECNICO" ,
    label: "TECNICO" },
  { value: "TECNICO DE FUTEBOL" ,
    label: "TECNICO DE FUTEBOL" },
  { value: "TECNICO DE INFORMATICA" ,
    label: "TECNICO DE INFORMATICA" },
  { value: "TECNICO DE SONDAGEM" ,
    label: "TECNICO DE SONDAGEM" },
  { value: "TECNICO EM ADMINISTRACAO" ,
    label: "TECNICO EM ADMINISTRACAO" },
  { value: "TECNICO EM AGRIMENSURA" ,
    label: "TECNICO EM AGRIMENSURA" },
  { value: "TECNICO EM CELULAR" ,
    label: "TECNICO EM CELULAR" },
  { value: "TECNICO EM CONTABILIDADE" ,
    label: "TECNICO EM CONTABILIDADE" },
  { value: "TECNICO EM EDIFICACOES" ,
    label: "TECNICO EM EDIFICACOES" },
  { value: "TECNICO EM ENFERMAGEM" ,
    label: "TECNICO EM ENFERMAGEM" },
  { value: "TECNICO EM LABORATORIO" ,
    label: "TECNICO EM LABORATORIO" },
  { value: "TECNICO EM MANUTENCAO" ,
    label: "TECNICO EM MANUTENCAO" },
  { value: "TECNICO EM METALURGICA" ,
    label: "TECNICO EM METALURGICA" },
  { value: "TECNICO EM RAIO X" ,
    label: "TECNICO EM RAIO X" },
  { value: "TECNICO EM TELEVISAO" ,
    label: "TECNICO EM TELEVISAO" },
  { value: "TECNICO AGRICOLA" ,
    label: "TECNICO AGRICOLA" },
  { value: "TECNICO AVIONICO" ,
    label: "TECNICO AVIONICO" },
  { value: "TECNICO ELETRONICO" ,
    label: "TECNICO ELETRONICO" },
  { value: "TECNICO ELETROTECNICO" ,
    label: "TECNICO ELETROTECNICO" },
  { value: "TECNICO INDUSTRIARIO" ,
    label: "TECNICO INDUSTRIARIO" },
  { value: "TECNICO MATERIA-PRIMA PLASTICO" ,
    label: "TECNICO MATERIA-PRIMA PLASTICO" },
  { value: "TECNICO OPERADOR" ,
    label: "TECNICO OPERADOR" },
  { value: "TECNICO REFRIGERACAO" ,
    label: "TECNICO REFRIGERACAO" },
  { value: "TECNICO SEGURANCA DE TRABALHO" ,
    label: "TECNICO SEGURANCA DE TRABALHO" },
  { value: "TECNICO TERMO PLASTICOS" ,
    label: "TECNICO TERMO PLASTICOS" },
  { value: "TECNICO ULTRA-SOM" ,
    label: "TECNICO ULTRA-SOM" },
  { value: "TECNOLOGO" ,
    label: "TECNOLOGO" },
  { value: "TECNOLOGO DE AUTOMAÇÃO" ,
    label: "TECNOLOGO DE AUTOMAÇÃO" },
  { value: "TELEFONISTA" ,
    label: "TELEFONISTA" },
  { value: "TELEGRAFISTA" ,
    label: "TELEGRAFISTA" },
  { value: "TELEMARKETING" ,
    label: "TELEMARKETING" },
  { value: "TERAPEUTA OCUPACIONAL" ,
    label: "TERAPEUTA OCUPACIONAL" },
  { value: "TESOUREIRO" ,
    label: "TESOUREIRO" },
  { value: "TINTUREIRO" ,
    label: "TINTUREIRO" },
  { value: "TOPOGRAFO" ,
    label: "TOPOGRAFO" },
  { value: "TORNEIRO FERRAMENTEIRO" ,
    label: "TORNEIRO FERRAMENTEIRO" },
  { value: "TORNEIRO MECANICO" ,
    label: "TORNEIRO MECANICO" },
  { value: "TOSADOR" ,
    label: "TOSADOR" },
  { value: "TRABALHADOR DA PECUARIA" ,
    label: "TRABALHADOR DA PECUARIA" },
  { value: "TRABALHADOR DA PESCA" ,
    label: "TRABALHADOR DA PESCA" },
  { value: "TRABALHADOR DA SUINOCULTURA" ,
    label: "TRABALHADOR DA SUINOCULTURA" },
  { value: "TRABALHADOR AGRICOLA" ,
    label: "TRABALHADOR AGRICOLA" },
  { value: "TRABALHADOR CONSTRUCAO CIVIL" ,
    label: "TRABALHADOR CONSTRUCAO CIVIL" },
  { value: "TRABALHADOR FLORESTAL" ,
    label: "TRABALHADOR FLORESTAL" },
  { value: "TRADUTOR INTERPRETE" ,
    label: "TRADUTOR INTERPRETE" },
  { value: "TRAINNE TECNICO" ,
    label: "TRAINNE TECNICO" },
  { value: "TREINADOR" ,
    label: "TREINADOR" },
  { value: "TREINADOR (A) NATAÇÃO" ,
    label: "TREINADOR (A) NATAÇÃO" },
  { value: "UNIVERSITARIO" ,
    label: "UNIVERSITARIO" },
  { value: "VAQUEIRO" ,
    label: "VAQUEIRO" },
  { value: "VENDEDOR" ,
    label: "VENDEDOR" },
  { value: "VENDEDOR  - RAMO DE SAPATOS" ,
    label: "VENDEDOR  - RAMO DE SAPATOS" },
  { value: "VENDEDOR  DE AUTO-PECAS" ,
    label: "VENDEDOR  DE AUTO-PECAS" },
  { value: "VENDEDOR (A) - FLIPERAMA" ,
    label: "VENDEDOR (A) - FLIPERAMA" },
  { value: "VENDEDOR (A) DE BARCOS" ,
    label: "VENDEDOR (A) DE BARCOS" },
  { value: "VENDEDOR -  ATACADO DE DOCES" ,
    label: "VENDEDOR -  ATACADO DE DOCES" },
  { value: "VENDEDOR - MATERIAL CONSTRUCAO" ,
    label: "VENDEDOR - MATERIAL CONSTRUCAO" },
  { value: "VENDEDOR - MATERIAL ELETRICO" ,
    label: "VENDEDOR - MATERIAL ELETRICO" },
  { value: "VENDEDOR - PAPELARIA" ,
    label: "VENDEDOR - PAPELARIA" },
  { value: "VENDEDOR - PLANO DE SAUDE" ,
    label: "VENDEDOR - PLANO DE SAUDE" },
  { value: "VENDEDOR - RAMO DE ALIMENTOS" ,
    label: "VENDEDOR - RAMO DE ALIMENTOS" },
  { value: "VENDEDOR - RAMO DE MARMORES" ,
    label: "VENDEDOR - RAMO DE MARMORES" },
  { value: "VENDEDOR - RAMO ELETRONICOS" ,
    label: "VENDEDOR - RAMO ELETRONICOS" },
  { value: "VENDEDOR - RAMO LABORATORIO" ,
    label: "VENDEDOR - RAMO LABORATORIO" },
  { value: "VENDEDOR DE BEBIDAS" ,
    label: "VENDEDOR DE BEBIDAS" },
  { value: "VENDEDOR DE BRINQUEDOS" ,
    label: "VENDEDOR DE BRINQUEDOS" },
  { value: "VENDEDOR DE CARVAO" ,
    label: "VENDEDOR DE CARVAO" },
  { value: "VENDEDOR DE CONSÓRCIO" ,
    label: "VENDEDOR DE CONSÓRCIO" },
  { value: "VENDEDOR DE GADO" ,
    label: "VENDEDOR DE GADO" },
  { value: "VENDEDOR DE MINIATURAS" ,
    label: "VENDEDOR DE MINIATURAS" },
  { value: "VENDEDOR DE PEDRAS PRECIOSAS" ,
    label: "VENDEDOR DE PEDRAS PRECIOSAS" },
  { value: "VENDEDOR DE PERSIANAS" ,
    label: "VENDEDOR DE PERSIANAS" },
  { value: "VENDEDOR DE PNEUS" ,
    label: "VENDEDOR DE PNEUS" },
  { value: "VENDEDOR DE POCOS ARTESIANOS" ,
    label: "VENDEDOR DE POCOS ARTESIANOS" },
  { value: "VENDEDOR DE ROUPAS" ,
    label: "VENDEDOR DE ROUPAS" },
  { value: "VENDEDOR DE TINTAS" ,
    label: "VENDEDOR DE TINTAS" },
  { value: "VENDEDOR DE TV A CABO" ,
    label: "VENDEDOR DE TV A CABO" },
  { value: "VENDEDOR DE VEICULOS" ,
    label: "VENDEDOR DE VEICULOS" },
  { value: "VENDEDOR AMBULANTE" ,
    label: "VENDEDOR AMBULANTE" },
  { value: "VENDEDOR AUT. BILHETE LOTERIA" ,
    label: "VENDEDOR AUT. BILHETE LOTERIA" },
  { value: "VENDEDOR AUTONOMO DE LINGERIE" ,
    label: "VENDEDOR AUTONOMO DE LINGERIE" },
  { value: "VENDEDOR ESTOF E COLCHÕES" ,
    label: "VENDEDOR ESTOF E COLCHÕES" },
  { value: "VENDEDOR ESTRUTURAS METALICAS" ,
    label: "VENDEDOR ESTRUTURAS METALICAS" },
  { value: "VENDEDOR MATERIAL HOSPITALAR" ,
    label: "VENDEDOR MATERIAL HOSPITALAR" },
  { value: "VENDEDOR NAUTICO" ,
    label: "VENDEDOR NAUTICO" },
  { value: "VENDEDOR PRODUTOS PLASTICOS" ,
    label: "VENDEDOR PRODUTOS PLASTICOS" },
  { value: "VENDEDOR RADIADORES/COLMEIAS" ,
    label: "VENDEDOR RADIADORES/COLMEIAS" },
  { value: "VENDEDOR TECNICO" ,
    label: "VENDEDOR TECNICO" },
  { value: "VENDEDOR(A) - FARMACEUTICO" ,
    label: "VENDEDOR(A) - FARMACEUTICO" },
  { value: "VENDEDOR(A) - PRODUTOS BELEZA" ,
    label: "VENDEDOR(A) - PRODUTOS BELEZA" },
  { value: "VENDEDOR(A) DE CIGARROS" ,
    label: "VENDEDOR(A) DE CIGARROS" },
  { value: "VENDEDORA DE LIVROS" ,
    label: "VENDEDORA DE LIVROS" },
  { value: "VEREADOR" ,
    label: "VEREADOR" },
  { value: "VETERINARIO" ,
    label: "VETERINARIO" },
  { value: "VIDRACEIRO" ,
    label: "VIDRACEIRO" },
  { value: "VIGIA" ,
    label: "VIGIA" },
  { value: "VIGILANTE" ,
    label: "VIGILANTE" },
  { value: "VISTORIADOR" ,
    label: "VISTORIADOR" },
  { value: "WEB DESIGNER" ,
    label: "WEB DESIGNER" },
  { value: "ZELADOR / CASEIRO" ,
    label: "ZELADOR / CASEIRO" },
  { value: "ZOOTECNISTA" ,
    label: "ZOOTECNISTA" },
  { value: "1/2 OFICIAL MONTAGEM" ,
    label: "1/2 OFICIAL MONTAGEM" },
];
export default occupations;