export const occupations = [
  {
    occupation: "Não informado",
  },
  {
    occupation: "ACOUGUEIRO",
  },
  {
    occupation: "ADESTRADOR DE CÃES",
  },
  {
    occupation: "ADM EMPRESA CHEFE ALMOXARIFADO",
  },
  {
    occupation: "ADM EMPRESAS - COM. EXTERIOR",
  },
  {
    occupation: "ADM EMPRESAS - MARKETING",
  },
  {
    occupation: "ADM EMPRESAS ELETRO ELETRONICO",
  },
  {
    occupation: "ADM. DE EMPRESA - IMPORT/EXPO",
  },
  {
    occupation: "ADM. EMPRESA - CARTAO CREDITO",
  },
  {
    occupation: "ADM. EMPRESA - CONSULTORIA",
  },
  {
    occupation: "ADM. EMPRESA - RECURSO HUMANOS",
  },
  {
    occupation: "DM. EMPRESAS - AG. DE TURISMO",
  },
  {
    occupation: "ADM. EMPRESAS - EDITORA",
  },
  {
    occupation: "ADM. EMPRESAS - EMBALAGENS",
  },
  {
    occupation: "ADM. EMPRESAS - LIMPEZA",
  },
  {
    occupation: "ADM. EMPRESAS - RAMO ESCOLA",
  },
  {
    occupation: "DM. EMPRESAS - RAMO SEGURANÇA",
  },
  {
    occupation: "ADM.DE EMPRESAS-EMP.BORRACHA",
  },
  {
    occupation: "ADM.EMPR. - INST. ELETRICAS",
  },
  {
    occupation: "ADM.EMPRESA - TELECOMUNICACOES",
  },
  {
    occupation: "ADM.EMPRESA-RAMO  ALIMENTÍCIO",
  },
  {
    occupation: "ADM.EMPRESA-VENDA/LOCAÇÃO VEIC",
  },
  {
    occupation: "ADM.EMPRESAS - RAMO SEGUROS",
  },
  {
    occupation: "ADMINISTRADOR - BINGO",
  },
  {
    occupation: "ADMINISTRADOR - CORREIOS",
  },
  {
    occupation: "ADMINISTRADOR - FAZENDAS",
  },
  {
    occupation: "ADMINISTRADOR - ORG NÃO GORV",
  },
  {
    occupation: "ADMINISTRADOR DE CONDOMINIO",
  },
  {
    occupation: "ADMINISTRADOR DE EMPRESAS",
  },
  {
    occupation: "ADMINISTRADOR ESTOF E COLCHÕES",
  },
  {
    occupation: "ADMINISTRADOR FINANCEIRO",
  },
  {
    occupation: "ADMINISTRADOR RAMO INFORMATICA",
  },
  {
    occupation: "ADMINISTRADOR(A) DE BENS",
  },
  {
    occupation: "ADMINISTRADOR(A) CONSTRUTORA",
  },
  {
    occupation: "DMINISTRADORA DE CONTRATOS",
  },
  {
    occupation: "ADVOGADO",
  },
  {
    occupation: "AERONAUTA",
  },
  {
    occupation: "AEROVIARIO",
  },
  {
    occupation: "AGENTE DE SAUDE",
  },
  {
    occupation: "AGENTE DE SEGUROS",
  },
  {
    occupation: "AGENTE DE VIAGEM",
  },
  {
    occupation: "AGENTE FISCAL DE RENDA",
  },
  {
    occupation: "AGENTE PENITENCIÁRIO",
  },
  {
    occupation: "AGENTE TEC. DE ESTATISTICA",
  },
  {
    occupation: "AGRICULTOR",
  },
  {
    occupation: "AGRONOMO",
  },
  {
    occupation: "AGROPECUARISTA",
  },
  {
    occupation: "AJUDANTE DE METALURGICA",
  },
  {
    occupation: "AJUDANTE DE MOTORISTA",
  },
  {
    occupation: "AJUDANTE GERAL",
  },
  {
    occupation: "LFAIATE/COSTUREIRA",
  },
  {
    occupation: "ALINHADOR AUTOMOTIVO",
  },
  {
    occupation: "ALMOXARIFE",
  },
  {
    occupation: "ANALISTA DE COMÉRCIO EXTERIOR",
  },
  {
    occupation: "ANALISTA DE DEPTO. PESSOAL",
  },
  {
    occupation: "ANALISTA DE MATERIAIS",
  },
  {
    occupation: "ANALISTA DE PLANEJAMENTO",
  },
  {
    occupation: "ANALISTA DE PROGRAMACAO",
  },
  {
    occupation: "ANALISTA DE SEGURANÇA",
  },
  {
    occupation: "ANALISTA DE SINISTRO",
  },
  {
    occupation: "ANALISTA DE SISTEMAS",
  },
  {
    occupation: "ANALISTA DE SUPORTE",
  },
  {
    occupation: "ANALISTA DE TACOGRAFO",
  },
  {
    occupation: "ANALISTA CONTABIL",
  },
  {
    occupation: "ANALISTA FINANCEIRO",
  },
  {
    occupation: "ANESTESISTA",
  },
  {
    occupation: "APOSENTADO - DOENÇA/ACIDENTE",
  },
  {
    occupation: "APOSENTADO - TEMPO DE SERVIÇO",
  },
  {
    occupation: "APOSENTADO / PENSIONISTA",
  },
  {
    occupation: "ARMADOR DE FERRAGEM CONST CIV",
  },
  {
    occupation: "ARQUEÓLOGO",
  },
  {
    occupation: "ARQUITETO",
  },
  {
    occupation: "ARRUMADEIRA /CAMAREIRA",
  },
  {
    occupation: "ARTESA - CONFECCAO EM LA'",
  },
  {
    occupation: "ARTESAO",
  },
  {
    occupation: "ARTISTA PLASTICO",
  },
  {
    occupation: "ASSESSOR(A)  FINANCEIRO(A)",
  },
  {
    occupation: "ASSESSOR(A) DE MARKETING",
  },
  {
    occupation: "ASSESSOR(A) JURÍDICO",
  },
  {
    occupation: "ASSESSOR(A) PARLAMENTAR",
  },
  {
    occupation: "ASSESSOR(A) SINDICAL",
  },
  {
    occupation: "ASSESSORA DE SEGUROS",
  },
  {
    occupation: "ASSESSORIA DE MIGRACAO",
  },
  {
    occupation: "ASSISTENTE DE CAMERA",
  },
  {
    occupation: "ASSISTENTE DE DIRETORIA",
  },
  {
    occupation: "ASSISTENTE DE INVESTIMENTOS",
  },
  {
    occupation: "ASSISTENTE DE PRODUCAO",
  },
  {
    occupation: "ASSISTENTE DE PROGRAMACAO",
  },
  {
    occupation: "ASSISTENTE DE TESOURARIA",
  },
  {
    occupation: "ASSISTENTE DE VENDAS",
  },
  {
    occupation: "ASSISTENTE ADMINISTRATIVO",
  },
  {
    occupation: "ASSISTENTE COMERCIAL",
  },
  {
    occupation: "ASSISTENTE COMERCIO EXTERIOR",
  },
  {
    occupation: "ASSISTENTE CONTABIL",
  },
  {
    occupation: "ASSISTENTE DEPTO. PESSOAL",
  },
  {
    occupation: "ASSISTENTE EXECUTIVO",
  },
  {
    occupation: "ASSISTENTE OPERACIONAL",
  },
  {
    occupation: "DASSISTENTE SOCIAL",
  },
  {
    occupation: "ASSISTENTE TECNICO",
  },
  {
    occupation: "STRÔNOMO",
  },
  {
    occupation: "ATENDENTE COMERCIAL",
  },
  {
    occupation: "ATENDENTE ENFERMAGEM",
  },
  {
    occupation: "ATLETA AMADOR",
  },
  {
    occupation: "ATOR /ATRIZ",
  },
  {
    occupation: "ATUÁRIO",
  },
  {
    occupation: "AUDITOR",
  },
  {
    occupation: "AUTONOMO",
  },
  {
    occupation: "AUTONOMO - CARREGADOR",
  },
  {
    occupation: "AUTONOMO - COBRANCA DE TITULOS",
  },
  {
    occupation: "AUTONOMO - CRIADOR DE ANIMAIS",
  },
  {
    occupation: "AUTONOMO - MAQUINAS GRAFICAS",
  },
  {
    occupation: "AUTONOMO - RAMO MARCENARIA",
  },
  {
    occupation: "AUTONOMO - VENDEDOR DE BRINDES",
  },
  {
    occupation: "AUTONOMO - VENDEDOR CRISTAIS",
  },
  {
    occupation: "AUTONOMO CONSULTOR INFORMATICA",
  },
  {
    occupation: "AUTONOMO RAMO INVESTIMENTO",
  },
  {
    occupation: "AUTONOMO(A) PROMOTOR(A) EVENTO",
  },
  {
    occupation: "AUTONOMO-MANUTENÇÃO HIDRÁULICA",
  },
  {
    occupation: "AUTOR (A)",
  },
  {
    occupation: "AUTÔNOMO - CULINÁRIA",
  },
  {
    occupation: "AUTÔNOMO - VENDEDOR DECORAÇÃO",
  },
  {
    occupation: "AUX LARVICULTURA",
  },
  {
    occupation: "AUX. TECNICO DE REFRIGERACAO",
  },
  {
    occupation: "AUXILIAR",
  },
  {
    occupation: "AUXILIAR  ESTATIS. TRANSPORTE",
  },
  {
    occupation: "AUXILIAR DE BIBLIOTECA",
  },
  {
    occupation: "AUXILIAR DE COBRANCA",
  },
  {
    occupation: "AUXILIAR DE COZINHEIRO ( A )",
  },
  {
    occupation: "AUXILIAR DE DESELVOLVIMENTO",
  },
  {
    occupation: "AUXILIAR DE ELETRONICA",
  },
  {
    occupation: "AUXILIAR DE ENFERMAGEM",
  },
  {
    occupation: "AUXILIAR DE ESCRITORIO",
  },
  {
    occupation: "AUXILIAR DE LABORATORIO",
  },
  {
    occupation: "AUXILIAR DE MANUTENCAO",
  },
  {
    occupation: "AUXILIAR DE PRODUCAO",
  },
  {
    occupation: "AUXILIAR DE PROTETICO",
  },
  {
    occupation: "AUXILIAR DE SERVIÇOS - LIMPEZA",
  },
  {
    occupation: "AUXILIAR DE SERVIÇOS GERAIS",
  },
  {
    occupation: "AUXILIAR DE TESOURARIA",
  },
  {
    occupation: "AUXILIAR DE TOPOGRAFIA",
  },
  {
    occupation: "AUXILIAR ADMINISTRATIVO",
  },
  {
    occupation: "AUXILIAR COMERCIAL",
  },
  {
    occupation: "AUXILIAR CONTÁBIL",
  },
  {
    occupation: "AUXILIAR DEPOSITO AUTO-PECAS",
  },
  {
    occupation: "JAUXILIAR DEPOSITO MT. ELETRICO'",
  },
  {
    occupation: "UXILIAR DEPTO.  PESSOAL",
  },
  {
    occupation: "AUXILIAR DESPACHANTE",
  },
  {
    occupation: "AUXILIAR FINANCEIRO",
  },
  {
    occupation: "AUXILIAR JUDICIÁRIO",
  },
  {
    occupation: "AUXILIAR MONTADOR METALURGICA",
  },
  {
    occupation: "AUXILIAR NA REDE TELEFONICA",
  },
  {
    occupation: "AUXILIAR PRODUCAO - ESTOFADOS",
  },
  {
    occupation: "AUXILIAR TECN. TELECOMUNICACAO",
  },
  {
    occupation: "AUXILIAR TECNICO",
  },
  {
    occupation: "AUXILIAR TRIBUTARIO",
  },
  {
    occupation: "AVICULTOR",
  },
  {
    occupation: "BABA",
  },
  {
    occupation: "BAILARINO",
  },
  {
    occupation: "BALCONISTA",
  },
  {
    occupation: "BANCARIO",
  },
  {
    occupation: "BANQUEIRO",
  },
  {
    occupation: "BARBEIRO",
  },
  {
    occupation: "BARMAN",
  },
  {
    occupation: "BIBLIOTECARIO",
  },
  {
    occupation: "BIOLOGO",
  },
  {
    occupation: "BIOMEDICA",
  },
  {
    occupation: "BIOQUIMICO (A)",
  },
  {
    occupation: "BOMBEIRO",
  },
  {
    occupation: "BOMBEIRO HIDRAULICO/ENCANADOR",
  },
  {
    occupation: "BORRACHEIRO",
  },
  {
    occupation: "CABELEREIRO(A)",
  },
  {
    occupation: "CADASTRADOR",
  },
  {
    occupation: "CAIXA",
  },
  {
    occupation: "CALHEIRO",
  },
  {
    occupation: "CAMAREIRA",
  },
  {
    occupation: "CAMINHONEIRO",
  },
  {
    occupation: "CANTINEIRA ESCOLAR",
  },
  {
    occupation: "CANTOR",
  },
  {
    occupation: "CANTORA",
  },
  {
    occupation: "CARDIOLOGISTA",
  },
  {
    occupation: "CARPINTEIRO",
  },
  {
    occupation: "CARTEIRO",
  },
  {
    occupation: "CARTORARIO",
  },
  {
    occupation: "CASEIRO",
  },
  {
    occupation: "CAVALEIRO",
  },
  {
    occupation: "CENOTECNICO",
  },
  {
    occupation: "CHAVEIRO",
  },
  {
    occupation: "CIENTISTA",
  },
  {
    occupation: "CIENTISTA POLITICO",
  },
  {
    occupation: "CINEASTA",
  },
  {
    occupation: "CIRURGIAO DENTISTA",
  },
  {
    occupation: "CITRICULTOR",
  },
  {
    occupation: "CLASSIFICADOR DE COURO",
  },
  {
    occupation: "COBRADOR DE ONIBUS",
  },
  {
    occupation: "COMENTARISTA",
  },
  {
    occupation: "COMERCIÁRIO RAMO TRANSPORTES",
  },
  {
    occupation: "COMERCIANTE",
  },
  {
    occupation: "COMERCIANTE  - CONFECCAO",
  },
  {
    occupation: "COMERCIANTE  - RAMO AGRICOLA",
  },
  {
    occupation: "COMERCIANTE  MATERIAL ELETRICO",
  },
  {
    occupation: "COMERCIANTE - AGROPECUARIA",
  },
  {
    occupation: "COMERCIANTE - ARTESANATO",
  },
  {
    occupation: "COMERCIANTE - ATACADISTA",
  },
  {
    occupation: "COMERCIANTE - AUTO ELETRICO",
  },
  {
    occupation: "COMERCIANTE - BALAS E DOCES",
  },
  {
    occupation: "COMERCIANTE - BANCA DE REVISTA",
  },
  {
    occupation: "COMERCIANTE - BOMBONAS",
  },
  {
    occupation: "COMERCIANTE - CAFE",
  },
  {
    occupation: "COMERCIANTE - CASA DE RAÇÕES",
  },
  {
    occupation: "COMERCIANTE - CONSTRUCAO CIVIL",
  },
  {
    occupation: "COMERCIANTE - COUROS",
  },
  {
    occupation: "COMERCIANTE - ELETRODOMESTICO",
  },
  {
    occupation: "COMERCIANTE - FARMACIA",
  },
  {
    occupation: "COMERCIANTE - LJ. DE VEICULOS",
  },
  {
    occupation: "COMERCIANTE - LJ. ARMARINHOS",
  },
  {
    occupation: "COMERCIANTE - LJ. CONVENIENCIA",
  },
  {
    occupation: "COMERCIANTE - LOJA DE PLANTAS",
  },
  {
    occupation: "COMERCIANTE - LOJA DE TINTAS",
  },
  {
    occupation: "COMERCIANTE - LOJA PET SHOP",
  },
  {
    occupation: "COMERCIANTE - PECAS PARA MOTOS",
  },
  {
    occupation: "COMERCIANTE - PEDREIRA",
  },
  {
    occupation: "COMERCIANTE - PEIXARIA",
  },
  {
    occupation: "COMERCIANTE - PLÁSTICOS",
  },
  {
    occupation: "COMERCIANTE - PROD. ODONTOLOG.",
  },
  {
    occupation: "COMERCIANTE - PRODUTOS LIMPEZA",
  },
  {
    occupation: "COMERCIANTE - RAMO DE PADARIAS",
  },
  {
    occupation: "COMERCIANTE - RAMO ACRÍLICO",
  },
  {
    occupation: "COMERCIANTE - RAMO BUFFET",
  },
  {
    occupation: "COMERCIANTE - RAMO CONSTRUCAO",
  },
  {
    occupation: "COMERCIANTE - RAMO ELETRÔNICOS",
  },
  {
    occupation: "COMERCIANTE - RAMO IMOBILIARIA",
  },
  {
    occupation: "COMERCIANTE - RAMO INFORMATICA",
  },
  {
    occupation: "COMERCIANTE - RAMO JOIAS",
  },
  {
    occupation: "COMERCIANTE - RECICLAGEM",
  },
  {
    occupation: "COMERCIANTE - SUPERMERCADO",
  },
  {
    occupation: "COMERCIANTE - TURISMO",
  },
  {
    occupation: "COMERCIANTE - VAREJÃO",
  },
  {
    occupation: "COMERCIANTE DE CALCADOS",
  },
  {
    occupation: "COMERCIANTE DE CELULARES",
  },
  {
    occupation: "COMERCIANTE DE JOIAS",
  },
  {
    occupation: "COMERCIANTE DE LUBRIFICANTES",
  },
  {
    occupation: "COMERCIANTE DE PNEUS",
  },
  {
    occupation: "COMERCIANTE ABATEDOURO AVES",
  },
  {
    occupation: "COMERCIANTE ACESSORIOS P/ AUTO",
  },
  {
    occupation: "COMERCIANTE BAR E RESTAURANTE",
  },
  {
    occupation: "COMERCIANTE CORTINAS/PERSIANAS",
  },
  {
    occupation: "COMERCIANTE DEPOSITO DE PAPEL",
  },
  {
    occupation: "COMERCIANTE IMPLEM. AGRICOLAS",
  },
  {
    occupation: "COMERCIANTE LJ INSTR. MUSICAIS",
  },
  {
    occupation: "COMERCIANTE LOJA DE REFORMAS",
  },
  {
    occupation: "COMERCIANTE LOUCAS CERAMICAS",
  },
  {
    occupation: "COMERCIANTE MATERIAL SEGURANCA",
  },
  {
    occupation: "COMERCIANTE MOVEIS ESCRITORIO",
  },
  {
    occupation: "COMERCIANTE PAPELARIA / XEROX",
  },
  {
    occupation: "COMERCIANTE POSTO DE GASOLINA",
  },
  {
    occupation: "TMERCIANTE PRESENTES EM GERAL",
  },
  {
    occupation: "COMERCIANTE RAMO DE ALIMENTOS",
  },
  {
    occupation: "COMERCIANTE RAMO EMBALAGENS",
  },
  {
    occupation: "COMERCIANTE RAMO FERRAGENS",
  },
  {
    occupation: "COMERCIANTE RAMO MADEIRA",
  },
  {
    occupation: "COMERCIANTE RAMO RELOJOARIA",
  },
  {
    occupation: "COMERCIANTE SECOS E MOLHADOS",
  },
  {
    occupation: "COMERCIANTE SUCATAS",
  },
  {
    occupation: "COMERCIANTE- FITAS  VIDEO GAME",
  },
  {
    occupation: "COMERCIANTE-APARELHOS AUDITIVO",
  },
  {
    occupation: "COMERCIANTE-RAMO DE PARAFUSOS",
  },
  {
    occupation: "COMERCIANTE-RAMO DEDETIZAÇÃO",
  },
  {
    occupation: "COMERCIANTE-TAPECEIRO DE AUTO",
  },
  {
    occupation: "COMERCIARIO",
  },
  {
    occupation: "COMERCIARIO FUNCIONARIO VAREJO",
  },
  {
    occupation: "COMISSARIO(A) DE BORDO",
  },
  {
    occupation: "COMPOSITOR",
  },
  {
    occupation: "COMPRADOR",
  },
  {
    occupation: "COMUNICOLOGA",
  },
  {
    occupation: "CONFEITEIRA",
  },
  {
    occupation: "CONFERENTE",
  },
  {
    occupation: "CONFERENTE PORTUARIO",
  },
  {
    occupation: "CONSELHEIRO TUTELAR",
  },
  {
    occupation: "CONSTRUTOR CIVIL",
  },
  {
    occupation: "CONSULTOR",
  },
  {
    occupation: "CONSULTOR (A) MARKETING",
  },
  { occupation: "CONSULTOR - TRANSPORTE" },
  { occupation: "CONSULTOR DE MODA" },
  { occupation: "CONSULTOR DE RECURSOS HUMANOS" },
  { occupation: "CONSULTOR DE VENDAS" },
  { occupation: "CONSULTOR EM INFORMATICA" },
  { occupation: "CONSULTOR EM PLANOS PRODUCAO" },
  { occupation: "CONSULTOR ADMINISTRATIVO" },
  { occupation: "CONSULTOR EMPRESARIAL" },
  { occupation: "CONSULTOR FINANCEIRO" },
  { occupation: "CONSULTOR IMOBILIARIO" },
  { occupation: "CONSULTOR INDUSTRIAL" },
  { occupation: "CONSULTOR JURIDICO" },
  { occupation: "CONSULTOR TECNICO" },
  { occupation: "CONTABILISTA" },
  { occupation: "CONTADOR" },
  { occupation: "CONTINUISTA" },
  { occupation: "CONTINUO" },
  { occupation: "CONTROLER" },
  { occupation: "COORDENADOR" },
  { occupation: "COORDENADOR  DE QUALIDADE" },
  { occupation: "COORDENADOR DE ESPORTES" },
  { occupation: "COORDENADOR DE OBRAS" },
  { occupation: "COORDENADOR COMERCIAL" },
  { occupation: "COORDENADOR ESCOLAR" },
  { occupation: "COORDENADOR PROJETOS ESPECIAIS" },
  { occupation: "COPEIRO" },
  { occupation: "COREOGRAFO" },
  { occupation: "CORRETOR DE CAFE" },
  { occupation: "CORRETOR DE IMOVEIS" },
  { occupation: "CORRETOR DE SEGUROS" },
  { occupation: "CORRETOR DE VALORES" },
  { occupation: "COSTUREIRA (A)" },
  { occupation: "COZINHEIRO" },
  { occupation: "CUMIN" },
  { occupation: "DECORADOR" },
  { occupation: "DELEGADO DE POLICIA" },
  { occupation: "DEMONSTRADORA-EXPOSIÇÃO  AUTOS" },
  { occupation: "DENTISTA" },
  { occupation: "DEPILADORA" },
  { occupation: "DEPUTADO ESTADUAL" },
  { occupation: "DEPUTADO FEDERAL" },
  { occupation: "DESEMBARGADOR" },
  { occupation: "DESEMPREGADO" },
  { occupation: "DESENHISTA" },
  { occupation: "DESIGNER" },
  { occupation: "DESPACHANTE" },
  { occupation: "DIARISTA" },
  { occupation: "DIGITADORA" },
  { occupation: "DIPLOMATA" },
  { occupation: "DIRETOR DE COMPRAS" },
  { occupation: "DIRETOR DE EMPRESA" },
  { occupation: "DIRETOR DE ESCOLA" },
  { occupation: "DIRETOR DE TV" },
  { occupation: "DIRETOR DE VENDAS" },
  { occupation: "DIRETOR ADJUNTO" },
  { occupation: "DIRETOR AUTO-ESCOLA" },
  { occupation: "DIRETOR COMERCIAL" },
  { occupation: "DIRETOR FINANCEIRO" },
  { occupation: "DIRETOR GERAL" },
  { occupation: "DIRETOR INDUSTRIAL" },
  { occupation: "DIRETOR LEGISLATIVO" },
  { occupation: "DIRETOR RH" },
  { occupation: "DIRETOR SECRETARIO" },
  { occupation: "DIRETOR SUPERINTENDENTE" },
  { occupation: "DIRETOR TECNICO" },
  { occupation: "DIRETORA - CASA DE CULTURA" },
  { occupation: "DIRETORA PRESIDENTE" },
  { occupation: "DIRETORA SINDICAL" },
  { occupation: "DIVULGADORA DE PROD HIGIENICOS" },
  { occupation: "DO LAR" },
  { occupation: "ECOLOGISTA" },
  { occupation: "ECONOMISTA" },
  { occupation: "EDITOR" },
  { occupation: "EDITORA DE VIDEO" },
  { occupation: "ELETRICISTA" },
  { occupation: "ELETRICITARIO" },
  { occupation: "ELETROTECNICO" },
  { occupation: "EMBALADOR DE PECAS DE AUTO" },
  { occupation: "EMPREENDEDOR FRANQUIA" },
  { occupation: "EMPREGADA DOMESTICA / BABÁ / FAXINEIRA" },
  { occupation: "EMPREITEIRO DE OBRAS" },
  { occupation: "EMPRESÁRIO (A) - COMBUSTÍVEIS" },
  { occupation: "EMPRESÁRIO (A) - ILUMINAÇÃO" },
  { occupation: "EMPRESÁRIO (A) - INTERCÂMBIOS" },
  { occupation: "EMPRESÁRIO (A) - ISOPOR" },
  { occupation: "EMPRESÁRIO (A) - MICROFIL.DIG" },
  { occupation: "EMPRESÁRIO - ARTIGOS DE COURO" },
  { occupation: "EMPRESÁRIO - BRINDES PROMOC." },
  { occupation: "EMPRESÁRIO - CONSTRUÇÃO CIVIL" },
  { occupation: "EMPRESÁRIO - ESQ. METÁLICAS" },
  { occupation: "EMPRESÁRIO - FACTORING" },
  { occupation: "EMPRESÁRIO - MADEIREIRA" },
  { occupation: "EMPRESÁRIO - NAVIOS" },
  { occupation: "EMPRESÁRIO - RAMO DE ARTES" },
  { occupation: "EMPRESÁRIO - RAMO DE BLINDAGEM" },
  { occupation: "EMPRESÁRIO - RAMO DE CALÇADOS" },
  { occupation: "EMPRESÁRIO - RAMO PLÁSTICOS" },
  { occupation: "EMPRESÁRIO - RAMO RESTAURANTES" },
  { occupation: "EMPRESÁRIO - SALÃO DE BELEZA" },
  { occupation: "EMPRESÁRIO - TELECOMUNICAÇÕES" },
  { occupation: "EMPRESÁRIO(A)- IND.DE BOTOES" },
  { occupation: "EMPRESÁRIO-RAMO DE TURISMO" },
  { occupation: "EMPRESÁRIO-RAMO AR CONDICIONAD" },
  { occupation: "EMPRESÁRIO-RAMO LAVANDERIA" },
  { occupation: "EMPRES.PREST SERV VIGILANCIA PARTICULAR" },
  { occupation: "EMPRESARIA - DONA DE CARTORIO" },
  { occupation: "EMPRESARIA - RAMO IMOVEIS" },
  { occupation: "EMPRESARIA LOJA DE ARTESANATO" },
  { occupation: "EMPRESARIO" },
  { occupation: "EMPRESARIO  - MARMORARIA" },
  { occupation: "EMPRESARIO  - RAMO HOTEL" },
  { occupation: "EMPRESARIO  - VIDEO LOCADORA" },
  { occupation: "EMPRESARIO ( A ) - RAMO TEXTIL" },
  { occupation: "EMPRESARIO (A)   ART P/ FESTAS" },
  { occupation: "EMPRESARIO (A) - ASSESSORIA" },
  { occupation: "EMPRESARIO (A) - DISTR. FILMES" },
  { occupation: "EMPRESARIO (A) - ETIQ ADESIVAS" },
  { occupation: "EMPRESARIO (A) - PROD DE VIDEO" },
  { occupation: "EMPRESARIO (A) - RAMO DE SAÚDE" },
  { occupation: "EMPRESARIO (A) - TRANSPORTES" },
  { occupation: "EMPRESARIO (A) PRODS. QUIMICOS" },
  { occupation: "EMPRESARIO (A) RAMO DE TECIDOS" },
  { occupation: "EMPRESARIO (A) RAMO ENGENHARIA" },
  { occupation: "EMPRESARIO - AUTO POSTO" },
  { occupation: "EMPRESARIO - AVIOES" },
  { occupation: "EMPRESARIO - CASA DE CARNES" },
  { occupation: "EMPRESARIO - CASA NOTURNA" },
  { occupation: "EMPRESARIO - CLUBE RECREATIVO" },
  { occupation: "EMPRESARIO - DONO CONSTRUTORA" },
  { occupation: "EMPRESARIO - ENERGIA ELETRICA" },
  { occupation: "EMPRESARIO - FABRICA CARIMBOS" },
  { occupation: "EMPRESARIO - FABRICA PLASTICO" },
  { occupation: "EMPRESARIO - FUNERARIA" },
  { occupation: "EMPRESARIO - GRANJA" },
  { occupation: "EMPRESARIO - IMPLEM. AGRICOLAS" },
  { occupation: "EMPRESARIO - INST. DE ALARMES" },
  { occupation: "EMPRESARIO - INSTR. MUSICAIS" },
  { occupation: "EMPRESARIO - LJ. R$ 1,99" },
  { occupation: "EMPRESARIO - LOJA DE CELULAR" },
  { occupation: "EMPRESARIO - LOJA DE COLCHOES" },
  { occupation: "EMPRESARIO - LOJA DE ROUPAS" },
  { occupation: "EMPRESARIO - MOTEL" },
  { occupation: "EMPRESARIO - OFICINA MECANICA" },
  { occupation: "EMPRESARIO - PAISAGISMO" },
  { occupation: "EMPRESARIO - PET SHOP" },
  { occupation: "EMPRESARIO - RAMO DE ACADEMIA" },
  { occupation: "EMPRESARIO - RAMO DE ADVOCACIA" },
  { occupation: "EMPRESARIO - RAMO DE BORRACHAS" },
  { occupation: "EMPRESARIO - RAMO DE EVENTOS" },
  { occupation: "EMPRESARIO - RAMO DE MAQUINAS" },
  { occupation: "EMPRESARIO - RAMO DE MOVEIS" },
  { occupation: "EMPRESARIO - RAMO DE SEGUROS" },
  { occupation: "EMPRESARIO - RAMO DE VIDROS" },
  { occupation: "EMPRESARIO - RAMO ALIMENTICIO" },
  { occupation: "EMPRESARIO - RAMO ALUMINIO" },
  { occupation: "EMPRESARIO - RAMO AUTO-PECAS" },
  { occupation: "EMPRESARIO - RAMO AUTOMOTOR" },
  { occupation: "EMPRESARIO - RAMO CERAMICA" },
  { occupation: "EMPRESARIO - RAMO CONFECCAO" },
  { occupation: "EMPRESARIO - RAMO CONTABIL" },
  { occupation: "EMPRESARIO - RAMO COPIADORA" },
  { occupation: "EMPRESARIO - RAMO DECORACAO" },
  { occupation: "EMPRESARIO - RAMO ESPORTES" },
  { occupation: "EMPRESARIO - RAMO ESTETICA" },
  { occupation: "EMPRESARIO - RAMO ESTOFARIA" },
  { occupation: "EMPRESARIO - RAMO FOTOGRAFIA" },
  { occupation: "EMPRESARIO - RAMO GRAFICA" },
  { occupation: "EMPRESARIO - RAMO INFORMATICA" },
  { occupation: "EMPRESARIO - RAMO LIVRARIA" },
  { occupation: "EMPRESARIO - RAMO LOGISTICA" },
  { occupation: "EMPRESARIO - RAMO LOTERIA" },
  { occupation: "EMPRESARIO - RAMO MARCENARIA" },
  { occupation: "EMPRESARIO - RAMO MOTOBOYS" },
  { occupation: "EMPRESARIO - RAMO OTICA" },
  { occupation: "EMPRESARIO - RAMO PADARIA" },
  { occupation: "EMPRESARIO - RAMO PALMILHAS" },
  { occupation: "EMPRESARIO - RAMO PIZZARIA" },
  { occupation: "EMPRESARIO - RAMO PUBLICIDADE" },
  { occupation: "EMPRESARIO - RAMO TELEFONIA" },
  { occupation: "EMPRESARIO - RAMO VIGILANCIA" },
  { occupation: "EMPRESARIO - SERVICOS GERAIS" },
  { occupation: "EMPRESARIO APARELHO CIRURGICO" },
  { occupation: "EMPRESARIO COM PESCA E NAUTICA" },
  { occupation: "EMPRESARIO COMUNICACAO VISUAL" },
  { occupation: "EMPRESARIO ESTRS METALICAS" },
  { occupation: "EMPRESARIO HIDRO IRRIGACAO" },
  { occupation: "EMPRESARIO IMPORT. EXPORTACAO" },
  { occupation: "EMPRESARIO IND. ENG.DE BEBIDAS" },
  { occupation: "EMPRESARIO MATERIAL CONSTRUCAO" },
  { occupation: "EMPRESARIO PRES SERV MANUTENC." },
  { occupation: "EMPRESARIO PRODS AGROPECUÁRIOS" },
  { occupation: "EMPRESARIO PRODUTO HOSPITALAR" },
  { occupation: "EMPRESARIO RAMO DE BRINQUEDOS" },
  { occupation: "EMPRESARIO RAMO DE COSMETICOS" },
  { occupation: "EMPRESARIO RAMO DE FARMACIA" },
  { occupations: "EMPRESARIO RAMO COBRANCA" },
  { occupations: "EMPRESARIO RAMO CONCESSIONARIA" },
  { occupations: "EMPRESARIO RAMO CONSULTORIA" },
  { occupations: "EMPRESARIO RAMO IMOBILIARIA" },
  { occupation: "EMPRESARIO RAMO MINERACAO" },
  { occupation: "EMPRESARIO RAMO SOFTWARE" },
  { occupation: "EMPRESARIO RAMO TERRAPLANAGEM" },
  { occupation: "EMPRESARIO RURAL" },
  { occupation: "EMPRESARIO SANEAMENTO E SERVS." },
  { occupation: "EMPRESARIO(A) - ESTACIONAMENTO" },
  { occupation: "EMPRESARIO(A) - FRIGORIFICO" },
  { occupation: "EMPRESARIO(A) - LOJA DE JOIAS" },
  { occupation: "EMPRESARIO(A) - METALURGICA" },
  { occupation: "EMPRESARIO(A) - RAMO ESCOLA" },
  { occupation: "EMPRESARIO(A) MANUT. INDUSTR." },
  { occupation: "EMPRESARIO-AGENCIA DE VIAGENS" },
  { occupation: "EMPRESARIO-PARQUE DE DIVERSÕES" },
  { occupation: "EMPRESARIO-RAMO DE BEBIDAS" },
  { occupation: "EMPRESARIO-RAMO DE MAGAZINE" },
  { occupation: "EMPRESARIO-RAMO DE MAGAZINE" },
  { occupation: "EMPRESARIO-RAMO HIPERMERCADO" },
  { occupation: "EMPRESARIO-SERVICOS MARITIMOS" },
  { occupation: "ENCADERNADOR" },
  { occupation: "ENCARREGADO (A ) FINANCEIRO (A" },
  { occupation: "ENCARREGADO DE COBRANCA" },
  { occupation: "ENCARREGADO DE DEPÓSITO" },
  { occupation: "ENCARREGADO DE MANUTENCAO" },
  { occupation: "ENCARREGADO DE OBRAS" },
  { occupation: "ENCARREGADO DE PRODUCAO" },
  { occupation: "ENCARREGADO DE TRANSPORTES" },
  { occupation: "ENCARREGADO DE USINAGEM" },
  { occupation: "ENCARREGADO DEPTO PESSOAL" },
  { occupation: "ENFERMEIRO" },
  { occupation: "ENGENHEIRO" },
  { occupation: "ENGENHEIRO - RAMO PETROLEO" },
  { occupation: "ENGENHEIRO DE PRODUCAO" },
  { occupation: "ENGENHEIRO DE REDES" },
  { occupation: "ENGENHEIRO DE SISTEMAS" },
  { occupation: "ENGENHEIRO DE SOFTWARE" },
  { occupation: "ENGENHEIRO AGRONOMO" },
  { occupation: "ENGENHEIRO CARTOGRAFO" },
  { occupation: "ENGENHEIRO CIVIL" },
  { occupation: "ENGENHEIRO ELETRICO" },
  { occupation: "ENGENHEIRO ELETRONICO" },
  { occupation: "ENGENHEIRO INDUSTRIAL" },
  { occupation: "ENGENHEIRO MECANICO" },
  { occupation: "ENGENHEIRO METALURGICO" },
  { occupation: "ENGENHEIRO NAVAL" },
  { occupation: "ENGENHEIRO PLENO" },
  { occupation: "ENGENHEIRO QUIMICO" },
  { occupation: "ENGENHEIRO(A) ELETRICISTA" },
  { occupation: "ENGENHEIRO(A) MECANICO(A) TEXT" },
  { occupation: "ENOLOGO" },
  { occupation: "ENTREGADOR" },
  { occupation: "ESCREVENTE" },
  { occupation: "ESCRITOR" },
  { occupation: "ESCRITURARIO" },
  { occupation: "ESCRIVÃO" },
  { occupation: "ESCULTOR" },
  { occupation: "ESTAGIARIO" },
  { occupation: "ESTATÍSTICO" },
  { occupation: "ESTETICISTA" },
  { occupation: "ESTETICISTA" },
  { occupation: "ESTILISTA" },
  { occupation: "ESTIVADOR" },
  { occupation: "ESTOQUISTA" },
  { occupation: "ESTUDANTE" },
  { occupation: "FARMACEUTICO" },
  { occupation: "FATURISTA" },
  { occupation: "FAXINEIRO" },
  { occupation: "FAZENDEIRO" },
  { occupation: "FEIRANTE" },
  { occupation: "FERRAMENTEIRO" },
  { occupation: "FERROVIARIO" },
  { occupation: "FISCAL DE LOJA" },
  { occupation: "FISCAL DE RENDA" },
  { occupation: "FISCAL DE TRANSPORTES" },
  { occupation: "FISCAL DE TRIBUTOS" },
  { occupation: "FISICO" },
  { occupation: "FISIOTERAPEUTA" },
  { occupation: "FLORICULTOR" },
  { occupation: "FONOAUDIOLOGO" },
  { occupation: "FOTOGRAFO" },
  { occupation: "FRENTISTA" },
  { occupation: "FREZADOR" },
  { occupation: "FUNCIONARIO PUBLICO" },
  { occupation: "FUNDIDOR" },
  { occupation: "FUNILEIRO" },
  { occupation: "FURADOR RADIAL" },
  { occupation: "GARCOM" },
  { occupation: "GARIMPEIRO" },
  { occupation: "GEOGRAFO" },
  { occupation: "GEOLOGO" },
  { occupation: "GERENTE - AGENCIA BANCÁRIA" },
  { occupation: "GERENTE DE ASSISTÊNCIA TÉCNICA" },
  { occupation: "GERENTE DE CARGAS" },
  { occupation: "GERENTE DE COBRANÇA" },
  { occupation: "GERENTE DE CONDOMINIO" },
  { occupation: "GERENTE DE CONTAS" },
  { occupation: "GERENTE DE EXPEDICAO" },
  { occupation: "GERENTE DE EXPORTACAO CALCADOS" },
  { occupation: "GERENTE DE LOGISTICA" },
  { occupation: "GERENTE DE LOJA" },
  { occupation: "GERENTE DE MODA" },
  { occupation: "GERENTE DE OFICINA MECÂNICA" },
  { occupation: "GERENTE DE PROC. DE DADOS" },
  { occupation: "GERENTE DE PRODUÇÃO" },
  { occupation: "GERENTE DE PRODUTOS" },
  { occupation: "GERENTE DE PROJETOS" },
  { occupation: "GERENTE DE RECURSOS HUMANOS" },
  { occupation: "GERENTE DE RESTAURANTE" },
  { occupation: "GERENTE DE SUPORTE TECNICO" },
  { occupation: "GERENTE DE VENDAS" },
  { occupation: "GERENTE COMERCIAL" },
  { occupation: "GERENTE CUSTO/ORCAMENTO" },
  { occupation: "GERENTE FINANCEIRO" },
  { occupation: "GERENTE FISCAL" },
  { occupation: "GERENTE INDUSTRIAL" },
  { occupation: "GERENTE MARKETING" },
  { occupation: "GERENTE TELECOMUNICACOES" },
  { occupation: "GERENTE TERRITORIO" },
  { occupation: "GESSEIRO" },
  { occupation: "GEÔMETRA" },
  { occupation: "GOVERNANTA" },
  { occupation: "GRAFICO" },
  { occupation: "GUARDA" },
  { occupation: "GUARDA MUNICIPAL" },
  { occupation: "GUIA TURISTICO" },
  { occupation: "ILUMINOTECNICO" },
  { occupation: "IMPRESSOR GRAFICO" },
  { occupation: "INDUSTRIAL" },
  { occupation: "INDUSTRIAL DE CALCADOS" },
  { occupation: "INDUSTRIARIO" },
  { occupation: "INDUSTRIARIO RAMO REFINARIA" },
  { occupation: "INSPETOR DE ALUNOS" },
  { occupation: "INSPETOR DE LABORATORIO" },
  { occupation: "INSPETOR DE RECEBIMENTOS" },
  { occupation: "INSPETOR DE SEGURANCA" },
  { occupation: "INSPETOR ADMINISTRATIVO" },
  { occupation: "INSPETOR CONTROLE DE QUALIDADE" },
  { occupation: "INSPETOR RAMO TRANSPORTES" },
  { occupation: "INSPETOR TECNICO" },
  { occupation: "INSTALADOR DE ANTENA" },
  { occupation: "INSTALADOR DE BOX" },
  { occupation: "INSTALADOR DE CALHAS" },
  { occupation: "INSTALADOR DE PAINEIS" },
  { occupation: "INSTALADOR DE PERSIANAS" },
  { occupation: "INSTRUMENTADOR(A)  CIRURGICO(A)" },
  { occupation: "INSTRUTOR" },
  { occupation: "INSTRUTOR DE AUTO ESCOLA" },
  { occupation: "INSTRUTOR DE BASQUETE" },
  { occupation: "INSTRUTOR DE JUDO" },
  { occupation: "INSTRUTOR DE TENIS" },
  { occupation: "INSTRUTOR DE VOLEI" },
  { occupation: "INVESTIGADOR DE POLICIA" },
  { occupation: "JARDINEIRO" },
  { occupation: "JOALHEIRO" },
  { occupation: "JOCKEY" },
  { occupation: "JOGADOR DE FUTEBOL" },
  { occupation: "JORNALEIRO" },
  { occupation: "JORNALISTA" },
  { occupation: "JUIZ DE DIREITO" },
  { occupation: "LANTERNEIRO" },
  { occupation: "LAVADOR DE AUTOMOVEIS" },
  { occupation: "LELOEIRO" },
  { occupation: "LIDER DE CONTROLE DE QUALIDADE" },
  { occupation: "LIDER DE MONTAGEM" },
  { occupation: "LOCUTOR" },
  { occupation: "LUTHIER" },
  { occupation: "MAGISTRADO" },
  { occupation: "MAGISTRADO FEDERAL" },
  { occupation: "MAITRE" },
  { occupation: "MANDRILHADOR" },
  { occupation: "MANICURE / PEDICURE / PODOLOGO /" },
  { occupation: "MANOBRISTA" },
  { occupation: "MAQUIADORA" },
  { occupation: "MARCENEIRO" },
  { occupation: "MARCHAND" },
  { occupation: "MARINHEIRO" },
  { occupation: "MARKETING PROMOCIONAL" },
  { occupation: "MARMORISTA" },
  { occupation: "MARQUETOLOGA" },
  { occupation: "MASSAGISTA" },
  { occupation: "MASSOTERAPEUTA" },
  { occupation: "MATEMATICO" },
  { occupation: "MECANICO" },
  { occupation: "MECANICO DE MANUTENCAO" },
  { occupation: "MECANICO DIESEL" },
  { occupation: "MEDICO" },
  { occupation: "MEDICO (A) ANESTESISTA" },
  { occupation: "MEDICO(A) OFTALMOLOGISTA" },
  { occupation: "MEDICO(A) RADIOLOGISTA" },
  { occupation: "MENSAGEIRO" },
  { occupation: "MERCADÓLOGO" },
  { occupation: "MESTRE DE OBRAS" },
  { occupation: "METALURGICO" },
  { occupation: "METEOROLOGISTA" },
  { occupation: "METROVIÁRIO" },
  { occupation: "METROVIÁRIO - BILHETERIA" },
  { occupation: "MICRO EMPRESARIO" },
  { occupation: "MICRO-EMPRES AUTOM. INDUSTRIAL" },
  { occupation: "MICRO-EMPRESARIO ESC. INFANTIL" },
  { occupation: "MILITAR" },
  { occupation: "MODELISTA" },
  { occupation: "MODELISTA DE CALCADOS" },
  { occupation: "MODELO / MANEQUIM" },
  { occupation: "MONITORA DE CRECHES" },
  { occupation: "MONTADOR DE ESTEIRAS" },
  { occupation: "MONTADOR DE FOTOLITO" },
  { occupation: "MORDOMO" },
  { occupation: "MOTOBOY" },
  { occupation: "MOTORISTA" },
  { occupation: "MUSEOLOGA" },
  { occupation: "MUSICO" },
  { occupation: "NIVELADOR" },
  { occupation: "NUTRICIONISTA" },
  { occupation: "ODONTOLOGO" },
  { occupation: "OFFICE BOY" },
  { occupation: "OFICIAL DA MARINHA" },
  { occupation: "OFICIAL DE JUSTICA" },
  { occupation: "OPERADOR (A) BOLSA DE VALORES" },
  { occupation: "OPERADOR DE ARMAZEM" },
  { occupation: "OPERADOR DE AUDIO" },
  { occupation: "OPERADOR DE BOMBEAMENTO" },
  { occupation: "OPERADOR DE CAIXA" },
  { occupation: "OPERADOR DE ESCAVADEIRA" },
  { occupation: "OPERADOR DE MAQUINAS" },
  { occupation: "OPERADOR DE MONTAGEM" },
  { occupation: "OPERADOR DE OPEN" },
  { occupation: "OPERADOR DE PLANTA QUIMICA" },
  { occupation: "OPERADOR DE PROCESSAMENTO" },
  { occupation: "OPERADOR DE SISTEMAS" },
  { occupation: "OPERADOR DE TELECOMUNICAÇÕES" },
  { occupation: "OPERADOR DE TELEMARKETING" },
  { occupation: "OPERADOR DE VALORES" },
  { occupation: "OPERADOR COMERCIAL" },
  { occupation: "OPERADOR FINANCEIRO" },
  { occupation: "OPERADOR INDUSTRIAL" },
  { occupation: "OPERADOR PORTUARIO" },
  { occupation: "OPERARIO" },
  { occupation: "OPTICO" },
  { occupation: "ORIENTADORA EDUCACIONAL" },
  { occupation: "ORIENTADORA PEDAGOGICA" },
  { occupation: "ORTODONTISTA" },
  { occupation: "OURIVES" },
  { occupation: "PADEIRO" },
  { occupation: "PADRE / FREIRA / PASTOR" },
  { occupation: "PAISAGISTA" },
  { occupation: "PECUARISTA" },
  { occupation: "PEDAGOGO (A)" },
  { occupation: "PEDREIRO" },
  { occupation: "PENSIONISTA" },
  { occupation: "PERFUSIONISTA" },
  { occupation: "PERITO" },
  { occupation: "PERITO JUDICIAL" },
  { occupation: "PERITO(A) CRIMINAL" },
  { occupation: "PERSONAL TRAINER" },
  { occupation: "PESCADOR (A)" },
  { occupation: "PESPONTADOR DE CALCADOS" },
  { occupation: "PESQUISADOR" },
  { occupation: "PESQUISADOR DE MERCADO" },
  { occupation: "PESQUISADORA IPT" },
  { occupation: "PET SHOP" },
  { occupation: "PILOTO" },
  { occupation: "PILOTO DE EMBARCAÇÕES" },
  { occupation: "PILOTO AERONAVES/ NÃO REGULAR" },
  { occupation: "PILOTO AERONAVES/LINHA REGULAR" },
  { occupation: "PINTOR" },
  { occupation: "PISCICULTOR" },
  { occupation: "PODOLOGO" },
  { occupation: "POLICIAL" },
  { occupation: "PORTEIRO" },
  { occupation: "PORTUARIO" },
  { occupation: "PRATICO" },
  { occupation: "PREFEITO" },
  { occupation: "PRESIDENTE" },
  { occupation: "PRODUTOR DE EVENTOS" },
  { occupation: "PRODUTOR DE FLORES" },
  { occupation: "PRODUTOR RURAL PAISAGISMO" },
  { occupation: "PROFESSOR" },
  { occupation: "PROGRAMADOR DE PRODUCAO" },
  { occupation: "PROGRAMADOR DE SISTEMAS" },
  { occupation: "PROGRAMADOR VISUAL" },
  { occupation: "PROJETISTA" },
  { occupation: "PROMOTOR DE JUSTICA" },
  { occupation: "PROMOTOR DE VENDAS" },
  { occupation: "PROPAGANDISTA" },
  { occupation: "PROTETICO" },
  { occupation: "PSICOLOGO" },
  { occupation: "PSICOTERAPEUTA" },
  { occupation: "PSIQUIATRA" },
  { occupation: "PUBLICITARIO" },
  { occupation: "QUIMICO" },
  { occupation: "RADIALISTA" },
  { occupation: "RECEPCIONISTA" },
  { occupation: "REDATOR" },
  { occupation: "REITORIA ADMINISTRATIVA" },
  { occupation: "RELACOES PUBLICAS" },
  { occupation: "REPORTER FOTOGRÁFICO" },
  { occupation: "REPR. VENDAS - SUPERMERCADO" },
  { occupation: "REPRESENTANTE COMERCIAL" },
  { occupation: "REVISORA" },
  { occupation: "RITILINISTA" },
  { occupation: "ROTEIRISTA DE TV" },
  { occupation: "SAPATEIRO" },
  { occupation: "SARRAFEIRO" },
  { occupation: "SECRETARIA DA DIRETORIA" },
  { occupation: "SECRETARIA COMPRA  METALURGICA" },
  { occupation: "SECRETARIO ( A )" },
  { occupation: "SECURITARIO" },
  { occupation: "SEGURANCA" },
  { occupation: "SEPARADOR DE PECAS DE AUTO" },
  { occupation: "SERRALHEIRO" },
  { occupation: "SERVENTE" },
  { occupation: "SERVENTUARIO" },
  { occupation: "SERVIDOR (A) DA JUSTICA" },
  { occupation: "SERVIDOR PUBL. FED." },
  { occupation: "SEXADOR DE ANIMAIS EM GRANJA" },
  { occupation: "SIDERÚRGICO" },
  { occupation: "SOCIOLOGO" },
  { occupation: "SOLDADOR" },
  { occupation: "SUINOCULTOR" },
  { occupation: "SUPERINTENDENTE" },
  { occupation: "SUPERVISOR" },
  { occupation: "SUPERVISOR  OPERACOES PETROLEO" },
  { occupation: "SUPERVISOR  RAMO TRANSPORTES" },
  { occupation: "SUPERVISOR DE COMPRAS" },
  { occupation: "SUPERVISOR DE CONTAS A PAGAR" },
  { occupation: "SUPERVISOR DE EXP. AUTO PEÇAS" },
  { occupation: "SUPERVISOR DE MANUTENCAO" },
  { occupation: "SUPERVISOR DE PRODUCAO" },
  { occupation: "SUPERVISOR DE PROJETOS" },
  { occupation: "SUPERVISOR DE SUPRIMENTOS" },
  { occupation: "SUPERVISOR DE TREINAMENTO" },
  { occupation: "SUPERVISOR DE VENDAS" },
  { occupation: "SUPERVISOR DE VIGILANTE" },
  { occupation: "SUPERVISOR ADMINISTRATIVO" },
  { occupation: "SUPERVISOR SERV. MECANICOS" },
  { occupation: "TÉCNICO EM AÇÚCAR E ÁLCOOL" },
  { occupation: "TÉCNICO EM COUROS E CALÇADOS" },
  { occupation: "TÉCNICO AMBIENTAL" },
  { occupation: "TÉCNICO ESTETICISTA" },
  { occupation: "TABELIAO" },
  { occupation: "TATUADOR" },
  { occupation: "TAXISTA" },
  { occupation: "TECNICA EM COMPUTACAO" },
  { occupation: "TECNICA EM NUTRICAO" },
  { occupation: "TECNICO" },
  { occupation: "TECNICO DE FUTEBOL" },
  { occupation: "TECNICO DE INFORMATICA" },
  { occupation: "TECNICO DE SONDAGEM" },
  { occupation: "TECNICO EM ADMINISTRACAO" },
  { occupation: "TECNICO EM AGRIMENSURA" },
  { occupation: "TECNICO EM CELULAR" },
  { occupation: "TECNICO EM CONTABILIDADE" },
  { occupation: "TECNICO EM EDIFICACOES" },
  { occupation: "TECNICO EM ENFERMAGEM" },
  { occupation: "TECNICO EM LABORATORIO" },
  { occupation: "TECNICO EM MANUTENCAO" },
  { occupation: "TECNICO EM METALURGICA" },
  { occupation: "TECNICO EM RAIO X" },
  { occupation: "TECNICO EM TELEVISAO" },
  { occupation: "TECNICO AGRICOLA" },
  { occupation: "TECNICO AVIONICO" },
  { occupation: "TECNICO ELETRONICO" },
  { occupation: "TECNICO ELETROTECNICO" },
  { occupation: "TECNICO INDUSTRIARIO" },
  { occupation: "TECNICO MATERIA-PRIMA PLASTICO" },
  { occupation: "TECNICO OPERADOR" },
  { occupation: "TECNICO REFRIGERACAO" },
  { occupation: "TECNICO SEGURANCA DE TRABALHO" },
  { occupation: "TECNICO TERMO PLASTICOS" },
  { occupation: "TECNICO ULTRA-SOM" },
  { occupation: "TECNOLOGO" },
  { occupation: "TECNOLOGO DE AUTOMAÇÃO" },
  { occupation: "TELEFONISTA" },
  { occupation: "TELEGRAFISTA" },
  { occupation: "TELEMARKETING" },
  { occupation: "TERAPEUTA OCUPACIONAL" },
  { occupation: "TESOUREIRO" },
  { occupation: "TINTUREIRO" },
  { occupation: "TOPOGRAFO" },
  { occupation: "TORNEIRO FERRAMENTEIRO" },
  { occupation: "TORNEIRO MECANICO" },
  { occupation: "TOSADOR" },
  { occupation: "TRABALHADOR DA PECUARIA" },
  { occupation: "TRABALHADOR DA PESCA" },
  { occupation: "TRABALHADOR DA SUINOCULTURA" },
  { occupation: "TRABALHADOR AGRICOLA" },
  { occupation: "TRABALHADOR CONSTRUCAO CIVIL" },
  { occupation: "TRABALHADOR FLORESTAL" },
  { occupation: "TRADUTOR INTERPRETE" },
  { occupation: "TRAINNE TECNICO" },
  { occupation: "TREINADOR" },
  { occupation: "TREINADOR (A) NATAÇÃO" },
  { occupation: "UNIVERSITARIO" },
  { occupation: "VAQUEIRO" },
  { occupation: "VENDEDOR" },
  { occupation: "VENDEDOR  - RAMO DE SAPATOS" },
  { occupation: "VENDEDOR  DE AUTO-PECAS" },
  { occupation: "VENDEDOR (A) - FLIPERAMA" },
  { occupation: "VENDEDOR (A) DE BARCOS" },
  { occupation: "VENDEDOR -  ATACADO DE DOCES" },
  { occupation: "VENDEDOR - MATERIAL CONSTRUCAO" },
  { occupation: "VENDEDOR - MATERIAL ELETRICO" },
  { occupation: "VENDEDOR - PAPELARIA" },
  { occupation: "VENDEDOR - PLANO DE SAUDE" },
  { occupation: "VENDEDOR - RAMO DE ALIMENTOS" },
  { occupation: "VENDEDOR - RAMO DE MARMORES" },
  { occupation: "VENDEDOR - RAMO ELETRONICOS" },
  { occupation: "VENDEDOR - RAMO LABORATORIO" },
  { occupation: "VENDEDOR DE BEBIDAS" },
  { occupation: "VENDEDOR DE BRINQUEDOS" },
  { occupation: "VENDEDOR DE CARVAO" },
  { occupation: "VENDEDOR DE CONSÓRCIO" },
  { occupation: "VENDEDOR DE GADO" },
  { occupation: "VENDEDOR DE MINIATURAS" },
  { occupation: "VENDEDOR DE PEDRAS PRECIOSAS" },
  { occupation: "VENDEDOR DE PERSIANAS" },
  { occupation: "VENDEDOR DE PNEUS" },
  { occupation: "VENDEDOR DE POCOS ARTESIANOS" },
  { occupation: "VENDEDOR DE ROUPAS" },
  { occupation: "VENDEDOR DE TINTAS" },
  { occupation: "VENDEDOR DE TV A CABO" },
  { occupation: "VENDEDOR DE VEICULOS" },
  { occupation: "VENDEDOR AMBULANTE" },
  { occupation: "VENDEDOR AUT. BILHETE LOTERIA" },
  { occupation: "VENDEDOR AUTONOMO DE LINGERIE" },
  { occupation: "VENDEDOR ESTOF E COLCHÕES" },
  { occupation: "VENDEDOR ESTRUTURAS METALICAS" },
  { occupation: "VENDEDOR MATERIAL HOSPITALAR" },
  { occupation: "VENDEDOR NAUTICO" },
  { occupation: "VENDEDOR PRODUTOS PLASTICOS" },
  { occupation: "VENDEDOR RADIADORES/COLMEIAS" },
  { occupation: "VENDEDOR TECNICO" },
  { occupation: "VENDEDOR(A) - FARMACEUTICO" },
  { occupation: "VENDEDOR(A) - PRODUTOS BELEZA" },
  { occupation: "VENDEDOR(A) DE CIGARROS" },
  { occupation: "VENDEDORA DE LIVROS" },
  { occupation: "VEREADOR" },
  { occupation: "VETERINARIO" },
  { occupation: "VIDRACEIRO" },
  { occupation: "VIGIA" },
  { occupation: "VIGILANTE" },
  { occupation: "VISTORIADOR" },
  { occupation: "WEB DESIGNER" },
  { occupation: "ZELADOR / CASEIRO" },
  { occupation: "ZOOTECNISTA" },
  { occupation: "1/2 OFICIAL MONTAGEM" },
];
export default occupations;
